### ISSUE TITLE
Add MAGMA continuous integration

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#107]
Lack of MAGMA CI is significantly slowing other project activities and runs a risk of the MAGMA backend ceasing to function due to other refactoring. The current backend only supports GPUs, but the MAGMA library is capable of targeting CPU code, so it should be possible to make it run on Travis-CI. Alternatively, we could use this gitlab-ci infrastructure that is being developed for ECP:
https://www.onyxpoint.com/account-level-ci-access-management-with-gitlab-setuid-runners/

**Comment by v-dobrev** [comment]
Does anyone know when the onyxpoint CI will be available?

**Comment by jedbrown** [comment]
I don't know. The pipeline is currently failing. ;-) https://gitlab.com/onyxpoint/gitlab-runner

**Comment by stomov** [comment]
Having a CI mechanism for the magma branch sounds good. What are the other branches using? We indeed run some routines on the CPU - if routine has vectors in the interface the run (and data) is on GPU (preferred), else, if we get pointer to scalar we check it and run on CPU in case of a CPU pointer, or GPU otherwise, e.g.,
static int CeedBasisApply_Magma(CeedBasis basis, CeedTransposeMode tmode,
	                        CeedEvalMode emode,
                                const CeedScalar *u, CeedScalar *v) {
  // If input scalar is on CPU, call CPU code                                                              
  if (magma_is_devptr(u)!=1)
      return CeedBasisApply_MagmaCPU(basis, tmode, emode, u, v);
  ...
In this case, is there a generic way to call the CEED CPU implementation (instead of copy of the code that we called CeedBasisApply_MagmaCPU)?
We did a next wave of performance optimizations but it was on the old interface. I am trying to catch up with current state and do a pull request.

**Comment by jedbrown** [comment]
Can you make `CeedInit_Magma` respond to `"/cpu/magma"` and then exclusively use CPU features (whether or not a GPU is present)? Then we can add it to Travis-CI.

Just dispatching into the reference backend wouldn't be testing MAGMA at all. We want to call MAGMA interfaces (to test as much of the MAGMA backend as possible), but have it execute on a CPU. In principle, the only difference would be that memory stays on the host.

**Comment by stomov** [comment]
Yes, we can do that (and will do) but will require some effort to do it nicely. As the CEED API evolves we see there is no need for us to duplicate certain routines anymore, e.g., CeedOperatorApply_Magma is the same as CeedOperatorApply, except that the vector operations use CeedMemType CEED_MEM_DEVICE instead of CEED_MEM_HOST. Down at the kernel level, code will be different and only there we can swap implementations based on what memory the pointers point to.

**Comment by jedbrown** [comment]
Yes, there is opportunity for reuse (and we should avoid copying and de-duplicate when possible), but different backends might want to batch and fuse differently so `CeedOperatorApply` needs to be implementable by each backend.

**Comment by jeremylt** [comment]
With the new MAGMA backend using delegation to the CUDA backend, it looks like this will be best covered when we get our GPU CI online.
