### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#109]
The documentation in `/doc` needs to be updated with active/passive sample code.

**Comment by jedbrown** [comment]
I think it is possible to designate blocks in a test or example (using Doxygen) and reference those from the documentation. See [`\snippet`](https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdsnippet). We should use that for all code samples in `doc/*.md` so that they are actual tested code, thus will remain current.

**Comment by jeremylt** [comment]
PR #118

**Comment by jedbrown** [comment]
The documentation refactoring in #118 addresses this issue.
