### ISSUE TITLE
Performance issues with `/gpu/cuda/magma` for non-tensor basis

### ISSUE THREAD

**Issue by zatkins-dev** [CEED/libCEED#1252]
JIT compilation of non-tensor basis code for `/gpu/cuda/magma` takes an excessive amount of time, especially for large values of `P`.
I believe this is due to the use of `#pragma unroll` in [`magma_common_nontensor.h`](https://github.com/CEED/libCEED/blob/main/include/ceed/jit-source/magma/magma_common_nontensor.h) for loops of length `P`, `Q`, or even `P*Q`. 

The results below, from a NVIDIA RTX 2070 Super with CUDA version 12.2, support this conclusion. I reproduced this slowdown on an NVIDIA A30 with CUDA version 12.1, although I do not have explicit timing results for that.

This issue was discussed with @nbeams on Zulip.

Current implementation (`CeedCompileMagma[in]` refers to the compilation for the `in`th non-tensor kernel instance):
```
P=8, Q=16
CeedCompileMagma[0] took 0 seconds 171 milliseconds
CeedCompileMagma[1] took 0 seconds 442 milliseconds
CeedCompileMagma[2] took 0 seconds 318 milliseconds
CeedCompileMagma[3] took 0 seconds 304 milliseconds
CeedCompileMagma[4] took 0 seconds 241 milliseconds
P=8, Q=16
CeedCompileMagma[0] took 0 seconds 175 milliseconds
CeedCompileMagma[1] took 0 seconds 437 milliseconds
CeedCompileMagma[2] took 0 seconds 318 milliseconds
CeedCompileMagma[3] took 0 seconds 298 milliseconds
CeedCompileMagma[4] took 0 seconds 242 milliseconds
P=64, Q=16
CeedCompileMagma[0] took 1 seconds 280 milliseconds
CeedCompileMagma[1] took 0 seconds 750 milliseconds
CeedCompileMagma[2] took 1 seconds 76 milliseconds
CeedCompileMagma[3] took 2 seconds 676 milliseconds
CeedCompileMagma[4] took 2 seconds 681 milliseconds
P=27, Q=16
CeedCompileMagma[0] took 0 seconds 472 milliseconds
CeedCompileMagma[1] took 0 seconds 666 milliseconds
CeedCompileMagma[2] took 0 seconds 687 milliseconds
CeedCompileMagma[3] took 0 seconds 595 milliseconds
CeedCompileMagma[4] took 0 seconds 977 milliseconds
P=8, Q=16
CeedCompileMagma[0] took 0 seconds 174 milliseconds
CeedCompileMagma[1] took 0 seconds 442 milliseconds
CeedCompileMagma[2] took 0 seconds 322 milliseconds
CeedCompileMagma[3] took 0 seconds 303 milliseconds
CeedCompileMagma[4] took 0 seconds 257 milliseconds
```

Without `#pragma unroll` in [`magma_common_nontensor.h`](https://github.com/CEED/libCEED/blob/main/include/ceed/jit-source/magma/magma_common_nontensor.h):
```
P=8, Q=16
CeedCompileMagma[0] took 0 seconds 169 milliseconds
CeedCompileMagma[1] took 0 seconds 560 milliseconds
CeedCompileMagma[2] took 0 seconds 408 milliseconds
CeedCompileMagma[3] took 0 seconds 364 milliseconds
CeedCompileMagma[4] took 0 seconds 242 milliseconds
P=8, Q=16
CeedCompileMagma[0] took 0 seconds 170 milliseconds
CeedCompileMagma[1] took 0 seconds 386 milliseconds
CeedCompileMagma[2] took 0 seconds 277 milliseconds
CeedCompileMagma[3] took 0 seconds 240 milliseconds
CeedCompileMagma[4] took 0 seconds 240 milliseconds
P=64, Q=16
CeedCompileMagma[0] took 0 seconds 426 milliseconds
CeedCompileMagma[1] took 0 seconds 437 milliseconds
CeedCompileMagma[2] took 0 seconds 408 milliseconds
CeedCompileMagma[3] took 0 seconds 509 milliseconds
CeedCompileMagma[4] took 0 seconds 501 milliseconds
P=27, Q=16
CeedCompileMagma[0] took 0 seconds 384 milliseconds
CeedCompileMagma[1] took 0 seconds 512 milliseconds
CeedCompileMagma[2] took 0 seconds 594 milliseconds
CeedCompileMagma[3] took 0 seconds 490 milliseconds
CeedCompileMagma[4] took 0 seconds 511 milliseconds
P=8, Q=16
CeedCompileMagma[0] took 0 seconds 170 milliseconds
CeedCompileMagma[1] took 0 seconds 382 milliseconds
CeedCompileMagma[2] took 0 seconds 271 milliseconds
CeedCompileMagma[3] took 0 seconds 239 milliseconds
CeedCompileMagma[4] took 0 seconds 238 milliseconds
```

**Comment by nbeams** [comment]
Hi @zatkins-dev, just to confirm, the times for P = 8 and P = 27 are also unacceptable for your uses?  E.g., too much compile time compared to how long the application will run/the lifetime of the basis object? Or no?

For P = 64, I realize, the problem is that we are compiling the kernels at all.  They are only meant to be used when P and Q are both less than the values defined in `ceed-magma.h` (currently 40):
```
#define MAGMA_NONTENSOR_CUSTOM_KERNEL_MAX_P (40)
#define MAGMA_NONTENSOR_CUSTOM_KERNEL_MAX_Q (40)
```
You can see how this check is used in `CeedBasisApplyNonTensor_Magma`:

```
 if (P < MAGMA_NONTENSOR_CUSTOM_KERNEL_MAX_P && Q < MAGMA_NONTENSOR_CUSTOM_KERNEL_MAX_Q) {
    [ launch the custom kernel... ]
      } else {
    [ call the magma_gemm_nontensor function, which uses standard library GEMM calls from MAGMA or cu/hipBLAS... ]
      }
```

So a simple fix would be to put guards around the compilation code in `CeedBasisCreateH1_Magma` when P or Q is too large. Should be everything from the `// Compile kernels` comment to the end of the loop marked with `// get kernels`.  We probably should've done this from the start, but I didn't think of it, as we didn't usually pay too much attention to compile time...

For the other orders, it looks like taking out the unroll doesn't make as much of a difference.  We'd want to make sure it doesn't affect the speed of the produced code before taking it out in all cases.

Another option to try for P < 40 is to reduce `MAGMA_NONTENSOR_KERNEL_INSTANCES` (also in `ceed-magma.h`) and keep the "N values" most applicable to your case -- e.g. since we often want to optimize performance at larger sizes, maybe change 

```
#define MAGMA_NONTENSOR_KERNEL_INSTANCES (5)
#define MAGMA_NONTENSOR_N_VALUES 10240, 51200, 102400, 512000, 1024000
```

to
```
#define MAGMA_NONTENSOR_KERNEL_INSTANCES (3)
#define MAGMA_NONTENSOR_N_VALUES 51200, 512000, 1024000
```

`N` in this case is (number of elements on GPU) * (number of components), to help you gauge which sizes are most relevant to you.

Again, we'd want to make sure that we are balancing time saved in compilation and the performance of the kernels, for your application. 

I can look more into this, especially if these options still aren't good enough for what you need, but I wanted to go ahead and share these thoughts in case you want to plow ahead and start investigating without me, rather than be stuck waiting on a reply.

**Comment by zatkins-dev** [comment]
> Hi @zatkins-dev, just to confirm, the times for P = 8 and P = 27 are also unacceptable for your uses? E.g., too much compile time compared to how long the application will run/the lifetime of the basis object? Or no?

The lifetime is the full application run, so we're only paying the compilation costs once per basis creation. For long runs, this would probably not be an issue, but for relatively small runs, the compile/startup time accounts for more than half of the total runtime. A large part of that is the `P = 64` case though, so if we can avoid the cost for `P > 40` , that may address the issue well enough.

I don't understand the rationale for unrolling these loops in the first place, though. The tensor basis magma kernels don't unroll loops, and the only other place that does is a single loop of the CUDA/HIP `gen` backends. The [CUDA programming guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html?highlight=pragma#pragma-unroll) also claims that small loops will be unrolled automatically.

> For the other orders, it looks like taking out the unroll doesn't make as much of a difference. We'd want to make sure it doesn't affect the speed of the produced code before taking it out in all cases.

My initial testing didn't show much of a difference in runtime performance, though I would be interested in a more comprehensive way to test that. 

> Another option to try for P < 40 is to reduce `MAGMA_NONTENSOR_KERNEL_INSTANCES` (also in `ceed-magma.h`) and keep the "N values" most applicable to your case -- e.g. since we often want to optimize performance at larger sizes, maybe change
> 
> ```
> #define MAGMA_NONTENSOR_KERNEL_INSTANCES (5)
> #define MAGMA_NONTENSOR_N_VALUES 10240, 51200, 102400, 512000, 1024000
> ```
> 
> to
> 
> ```
> #define MAGMA_NONTENSOR_KERNEL_INSTANCES (3)
> #define MAGMA_NONTENSOR_N_VALUES 51200, 512000, 1024000
> ```

This also seems like it would help substantially with compilation times, although I could see larger performance costs for smaller sizes outweighing that benefit.

**Comment by nbeams** [comment]
> I don't understand the rationale for unrolling these loops in the first place, though. The tensor basis magma kernels don't unroll loops, and the only other place that does is a single loop of the CUDA/HIP gen backends. The [CUDA programming guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html?highlight=pragma#pragma-unroll) also claims that small loops will be unrolled automatically.

I would tag in @abdelfattah83 on the question of "why unroll these loops," as he wrote the kernels. If the compile times are consistently different between the two versions, though, then I think that implies it must be doing something differently with the pragma and without? 

> though I would be interested in a more comprehensive way to test that.

I have a stand-alone tester (outside of libCEED itself, does not use nvrtc/hiprtc, but has the same kernel code and GEMM configurations) that we may be able to put to use for these purposes, if desired.

> This also seems like it would help substantially with compilation times, although I could see larger performance costs for smaller sizes outweighing that benefit.

I am curious about what range of sizes you most need -- generally, for larger runs, when deciding how many ranks to use, we want to have a larger (> ~1e5-ish? and bigger for HIP) number of elements per GPU in order to really make use of the hardware.  Will you need a large range of sizes?

Another thing we could potentially do would be to lazily compile the kernels.  The reason for the multiple kernels now is that we need to know the value of `N` at compile time...but `N` depends on the number of elements, which is a parameter of the basis apply function.  But, we could try setting it up so that nothing is compiled when the non-basis is created.  In the apply function, we figure out which instance we will need, check if it has been compiled yet, compile if necessary, and launch.

**Comment by zatkins-dev** [comment]
>  If the compile times are consistently different between the two versions, though, then I think that implies it must be doing something differently with the pragma and without?

To clarify, I'm not sure what "small loops" means to the CUDA compiler, so it's possible that some values, e.g. `P = 8`, are automatically unrolled while for others, e.g. `P = 27`, the compiler decides to keep it as a loop. That would explain the discrepancies between compiling with/without the pragma. 

> I am curious about what range of sizes you most need -- generally, for larger runs, when deciding how many ranks to use, we want to have a larger (> ~1e5-ish? and bigger for HIP) number of elements per GPU in order to really make use of the hardware. Will you need a large range of sizes?

I'm not entirely sure, maybe @jeremylt or @jedbrown can speak more to this.

**Comment by jedbrown** [comment]
Probably the most common is Q=14 followed by Q=24, which are minimal symmetric quadratures for second and third order tets. For CFD, we'll have cubic prisms, which have Q=48 because libCEED doesn't support tensorization of a triangle with a line. Note that cubic hexes need Q=64, but those should be computed using a `*/gen` backend when doing mixed topology.

**Comment by jeremylt** [comment]
I'm all for lazy patterns where we don't do anything until we are sure we need to. The LIBXSMM backend just got fixed to use that pattern and it's generally how we do everything else in the library.

**Comment by zatkins-dev** [comment]
> Can you spot any noticeable difference in the performance of the kernels without the #pragma unroll?

Not that I could see, although my performance testing is a bit lacking in precision. 

I think that reducing the number of kernel instances would be the most straightforward fix, especially if the `#pragma unroll` are useful for e.g. `hipcc`

**Comment by sebastiangrimberg** [comment]
> I'm all for lazy patterns where we don't do anything until we are sure we need to. The LIBXSMM backend just got fixed to use that pattern and it's generally how we do everything else in the library.

FYI I'm working on this in combination with non-tensor H(div) and H(curl) support for MAGMA. I haven't checked to see how much it helps the run time compilation overhead but have a branch which is passing all tests on V100 if that's of interest to play around with.

**Comment by sebastiangrimberg** [comment]
Hi @zatkins-dev, could you try https://github.com/CEED/libCEED/pull/1301 when you get a chance to see if this improves the issue? This does a few things: Compiles on the custom kernels for P, Q less than the specified threshold values (40), and also only builds the kernels for the value of N which is used during the first basis application (based on `num_elem` and `num_comp`).

**Comment by zatkins-dev** [comment]
> Hi @zatkins-dev, could you try #1301 when you get a chance to see if this improves the issue? This does a few things: Compiles on the custom kernels for P, Q less than the specified threshold values (40), and also only builds the kernels for the value of N which is used during the first basis application (based on `num_elem` and `num_comp`).

This is a huge improvement, thank you! I think that the lazy compilation made a huge difference.
