### ISSUE TITLE
`magma` backend `CeedElemRestriction`

### ISSUE THREAD

**Issue by sebastiangrimberg** [CEED/libCEED#1288]
It looks to me like the MAGMA backend implementation of `CeedElemRestriction` is very similar (if not basically the same?) as the fallback `cuda-ref` or `hip-ref` implementations. Can someone perhaps provide context for why it has a separate implementation or, as a separate question, would it make sense to remove the MAGMA implementations? This would be nicer for long term library maintainability as it would allow us to reduce some code duplication, and especially would make GPU backends for #1265 require fewer added lines of code. Of course if there is actually a reason for having the different implementations of `CeedElemRestriction` then I am all for keeping both.

**Comment by nbeams** [comment]
Starting with the short answer first: 
> would it make sense to remove the MAGMA implementations? 

I have been wondering this myself, lately.  If we did so, I think it would make the most sense to get rid of the `magma-det` backend and turn the `magma` backend into, essentially, the `magma-det` backend (but with simpler setup and shorter name). I'm not sure if that would be considered a major/breaking change or not?

The longer answer: 

The restrictions aren't exactly the same, as the MAGMA restrictions use atomic adds in the transpose restrictions, and the ref kernels do not.  Hence the distinction between the `magma` backend (not deterministic due to atomic adds) and `magma-det` (deterministic, uses MAGMA basis but ref restrictions).  I haven't studied it rigorously, but most of my tests over the past 2-ish years have indicated no real performance benefit to the version with atomics, so that's why I've been wondering if we should simplify and cut it, as you suggested.

As for why they exist, that's mostly just a remnant of libCEED development history.  At the time we added these restrictions to the `magma` backend, the other GPU backends used the same E-vector ordering as the CPU backends.  For the non-tensor basis calculations in MAGMA, we wanted to swap the E-vector ordering to have the layout we needed for the GEMMs.  So, we added our own restrictions to get the ordering we wanted.  Some time after this, we ended up switching the E-vector ordering of the other GPU backends to be the same as what MAGMA was using, which then allowed MAGMA to use the ref restrictions again, and added the `magma-det` backend which did just that.

**Comment by jeremylt** [comment]
I am fine with trimming out the MAGMA backend restrictions, though we should do a performance study first to make sure we aren't making a bad decision here. I'd be especially interested in seeing the performance study on non-tensor elements since that's the area where we really look to the MAGMA backend for performance.

**Comment by sebastiangrimberg** [comment]
Thanks for the response @nbeams and @jeremylt! That's very helpful and sorry for missing over the `atomicAdd` difference, good call out. I would perhaps propose adding a compile time option to make the `cuda-ref` and `hip-ref` `ElementRestriction` use `atomicAdd` in place of the deterministic variant, and then go ahead and trim the MAGMA backend restrictions. This way we aren't removing any functionality if it does turn out that `atomicAdd` leads to substantial speedup (we can leave this option off by default so that the baseline implementation is deterministic). I'd be happy to profile the differences as well and should be doing this soon anyways in related work.

**Comment by jeremylt** [comment]
Hmm, we try to not force the user to make too many decisions at compile time. I'm honestly not sure how I feel about making this a compile time option.

**Comment by sebastiangrimberg** [comment]
Yeah OK, that's definitely fair and I understand making it a compile time option goes against a lot of the library design. Let me see if I can think about maybe just some way to refactor it a bit to leave it as an option without total duplication of the kernels for the one line difference.

**Comment by nbeams** [comment]
The kernel in question (`OffsetTranspose`/`magma_writeDofsStrided_kernel`) is more than a one-line difference.  The computational strategy is different in the ref version, to ensure correctness without needing atomic adds.  It has more loops total and uses a temporary variable (`value[num_comp]`) which the MAGMA version doesn't use.

**Comment by sebastiangrimberg** [comment]
> The kernel in question (`OffsetTranspose`/`magma_writeDofsStrided_kernel`) is more than a one-line difference.  The computational strategy is different in the ref version, to ensure correctness without needing atomic adds.  It has more loops total and uses a temporary variable (`value[num_comp]`) which the MAGMA version doesn't use.

Sorry one line was an exaggeration here but I hope the point was clear enough 😃

**Comment by nbeams** [comment]
Haha oh no, you quoted me right as I fixed my kernel name typo... 😅

**Comment by sebastiangrimberg** [comment]
OK, I've got a proposal in https://github.com/CEED/libCEED/pull/1292. This uses the `CeedIsDeterministic` flag set by backends to JiT a deterministic vs. non-deterministic variant of the offset element restriction transpose operation at runtime. This removes the need for the separate `magma` backend restrictions so accomplishes the goal of reducing code duplication, while not adding any new compile time configuration complexity.

**Comment by jeremylt** [comment]
Fixed up in #1292
