### ISSUE TITLE
Mixed Diagonal Assembly

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#1342]
Unfortunately #1316 breaks critical functionality for Ratel - we need to be able to assemble diagonals with different numbers of active bases.

See #1150 

We either need to revert or fix this before we release.

**Comment by jeremylt** [comment]
It looks non-trivial to fix this, so for now I'm making a PR to revert the regression.

**Comment by sebastiangrimberg** [comment]
The changes to diagonal assembly might be able to be reverted without reverting the entire PR. Let me see if I can take a look at this, I think I see the case which I had not anticipated. Prior to #1316 the diagonal code looped over `num_active_bases` which was the input and output bases together. So now that these are separate into `active_bases_in` and `active_bases_out`, I think we just need to modify that loop in `CeedSingleOperatorAssembleAddDiagonal_Core` without any changes to the new assembly data structures.

I haven't used Ratel but seems like it might be a good prerequisite to test that when developing, changes in libCEED don't break Ratel. Is there a way we can tes this in the CI?

**Comment by jedbrown** [comment]
I think this is a viable way to run a Ratel pipeline from within a libCEED pipeline (probably after the others). https://docs.gitlab.com/ee/ci/pipelines/downstream_pipelines.html

@sebastiangrimberg If you can try the change you have in mind, we can hold off on merging the revert PR #1343.

**Comment by sebastiangrimberg** [comment]
OK thanks for the chance to fix it. Question here for my understanding based on the original PR #1150:

If there is an active basis for the operator which is associated with the input but not output (or output but not input), then from my reading `num_eval_modes_out/in` will be zero for this basis as constructed in `CeedAssemblyDataCreate`. This means there's no contribution to the diagonal in the loop in `CeedSingleOperatorAssembleAddDiagonal_Core`. Is this correct?

So the current change from #1343 is "correct" in the sense that if the `active_bases_in` and `active_bases_out` arrays are sorted so that the first `min(num_active_bases_in, num_active_bases_out)` elements point to matching basis objects, we can just loop for `b = 0, b < min(num_active_bases_in, num_active_bases_out), b++` iterations.

Can you confirm my understanding of the use case of the multiple active bases with where the input and output active bases counts differ?

**Comment by jeremylt** [comment]
This is the offending operator:
```
CeedOperator - platen jacobian - face 5 orientation 4
  16 elements with 9 quadrature points each
  6 fields
  5 input fields:
    Input field 0:
      Name: "q data"
      Size: 13
      EvalMode: none
      No basis
    Input field 1:
      Name: "d(du)/dX, field 0"
      Size: 9
      EvalMode: gradient
      Active vector
    Input field 2:
      Name: "du, field 1"
      Size: 1
      EvalMode: interpolation
      Active vector
    Input field 3:
      Name: "du"
      Size: 3
      EvalMode: interpolation
      Active vector
    Input field 4:
      Name: "stored values platen"
      Size: 4
      EvalMode: none
      No basis
  1 output field:
    Output field 0:
      Name: "dv"
      Size: 3
      EvalMode: interpolation
      Active vector
```

Input field 1 is the gradient of displacement and input field 2 is pressure. But only displacement has an output. So there is no contribution to the operator diagonal for pressure for this suboperator.

But there is no convention forcing the users to add fields in any sorted way.  We may want/need to make such a convention in `CeedAssemblyData`, but I don't know if I did that or not.

**Comment by sebastiangrimberg** [comment]
Awesome thanks for this info, that makes sense. No need to do the sorting, that was just to try to explain myself so my question would make sense. Basically all I need to do is to match a given input and output basis in the assembly, which previously was done during the assembly data creation but now that the inputs and outputs are stored separately needs to be treated elsewhere. I'll have a fix shortly.

**Comment by sebastiangrimberg** [comment]
OK, sorry for the delay, I was on a flight and didn't have internet. But #1344 should fix the issue as I understand it, can you give it a go? Thanks so much.
