### ISSUE TITLE
Incorrect indexing for qd in Test 531

### ISSUE THREAD

**Issue by Jeff-Hadley** [CEED/libCEED#1589]
The symmetric components of the qw/det(J) Adj(J) * Ajd(J)^T operation are not being stored in the correct indices as described in the storage format comment of line 23 of [t531-operator.h](https://github.com/CEED/libCEED/blob/ef9a992f4cf09f2be4ec72f649495c67ec03f813/tests/t531-operator.h). Currently also affects the values being calculated in dv = qd * du. Indexing of qd of lines 31 and 32 need to be switched.  

@jrwrigh, as per our discussion, not sure if this also effects output checks in [t531-operator.c](https://github.com/CEED/libCEED/blob/ef9a992f4cf09f2be4ec72f649495c67ec03f813/tests/t531-operator.c) .

**Comment by jeremylt** [comment]
I don't think it should have any effect on the assembly checks. The assembly process shouldn't care about the contents of the QFunction

**Comment by jeremylt** [comment]
It looks like I wrote that header that way 5 years ago. I think it might have been a debugging change that slipped the cracks?

**Comment by jrwrigh** [comment]
Yeah, I don't think it necessarily changes the validity of the test from an assembly stand-point; but I think that's due to error cancellations and the fact that many of the values being multiplied are zero due to the constant initial condition and square grid.

Regardless, correcting the indexing still results in a passing test.

**Comment by jeremylt** [comment]
I think it works because the QFunction itself isn't relevant to the assembly logic. But in any case we should patch the bug

**Comment by rezgarshakeri** [comment]
I am not sure if that's bug. If you remember @jeremylt we talked about that few years ago. The way that tensor contract is written needs a transpose at the input and transpose at the output of the Qfunction. That's why all of the q-data is set to its transpose at the beginning of the code (see [here](https://github.com/CEED/libCEED/blob/ef9a992f4cf09f2be4ec72f649495c67ec03f813/examples/fluids/qfunctions/setupgeo_helpers.h#L95) for example we have `dxdX_21 = dxdX_q[0][1][i];`).

 `t531` has zero off-diagonal in jacobian that's why doesn't affect the test if you switch the index (uniform element). You can check the value of the q-data with a code in python/julia for non-affine element and we need to set index like that to get correct jacobian (I had a test for that and I need to find it)

**Comment by jeremylt** [comment]
It's inconsistent with the ordering given in the Gallery

**Comment by rezgarshakeri** [comment]
Oh, you are talking about the comment, I thought you want to change the index of `J12, J21` here
```
    const CeedScalar J11 = J[i + Q * 0];
    const CeedScalar J21 = J[i + Q * 1];
    const CeedScalar J12 = J[i + Q * 2];
    const CeedScalar J22 = J[i + Q * 3];
```

**Comment by jeremylt** [comment]
The comment and/or how it's packed into the 1x3 format for storage

**Comment by rezgarshakeri** [comment]
Ah, okay, sorry. I thought it is about indexing of the input and wanted to mention that we need to read the transpose of the input to get correct jacobian.

**Comment by jeremylt** [comment]
The more I think the more I think changing the comment and not calling it a Poison is the way you go so we still get zero and nonzero entries but it keeps nonzero off diagonals

**Comment by jrwrigh** [comment]
You could also keep the Poisson nature of it and just perturb a single node such that the off-diagonal entry is non-zero for at least one element. Like, instead of the first node being at $$(0,0)$$, make it at $$(-0.5, -1)$$.

**Comment by jrwrigh** [comment]
> `t531` has zero off-diagonal in jacobian that's why doesn't affect the test if you switch the index (uniform element).

I think it's that and the solution gradient itself is also 0 since it's just a constant function over the domain.
