### ISSUE TITLE
Add CeedVectorSyncArray

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#162]
We need to add a new frontend function `CeedVectorSyncArray` to signal to GPU backends that CeedVector data needs to be pushed to the host.

**Comment by YohannDudouit** [comment]
I understand the need for such a functionality, but I think we should be careful on how we implement this, a convenient implementation might reveal to be especially bug prone. Do you have in mind a proposition on what form this synchronisation would have in term of code?

**Comment by jeremylt** [comment]
Implementation would depend upon the specific backend. I am imagining this being just a way for the user to demand that the host be updated with data from the device, for whatever reason. The backend gets to decide how that works.

**Comment by YohannDudouit** [comment]
I mean, did you have an interface in mind? The kind of bugs I was thinking of already arise at the interface level.

**Comment by jeremylt** [comment]
I'm not sure what you mean. All I imagine adding to the frontend is `CeedVectorSync(CeedVector v)`. The backend then would make sure that the data on the host matches the data on the device via whatever means is most appropriate. I know nothing about the best way to copy data from the device to the host.

My hope is that this would let GPU backends only update the host pointer when requested.

Here is some sample user code I'm thinking of in the context of the PETSc example:

```
  ierr = VecGetArrayRead(user->Xloc, (const PetscScalar**)&x); CHKERRQ(ierr);
  ierr = VecGetArray(user->Yloc, &y); CHKERRQ(ierr);
  CeedVectorSetArray(user->xceed, CEED_MEM_HOST, CEED_USE_POINTER, x);
  CeedVectorSetArray(user->yceed, CEED_MEM_HOST, CEED_USE_POINTER, y);

  CeedOperatorApply(user->op, user->xceed, user->yceed,
                    CEED_REQUEST_IMMEDIATE);
  CeedVectorSync(user->yceed);
```

And for the Nek example:

```
      call ceedvectorsetarray(vec_ap1,ceed_mem_host,ceed_use_pointer,
     $  ap1,err)
       call ceedoperatorapply(op_mass,vec_p1,vec_ap1,	
     $  ceed_request_immediate,err)
       call ceedvectorsync(vec_ap1,err)
```

I am hoping this new function clarifies when communication between host and device is required, removing extra communication.

**Comment by YohannDudouit** [comment]
I'm not sure I understand, do you assume that a `CeedVector` would contain both the data on GPU and on CPU (regardless of your `CEED_MEM_HOST` flag), and that calling `CeedVectorSync(v)` would synchronise the data on CPU and on GPU (regardless if it's a pull or a push of data)?

**Comment by jedbrown** [comment]
If you provided an array with CeedVectorSetArray and either CEED_USE_POINTER or CEED_OWN_POINTER, then CeedVectorSync would ensure that the provided array contains current values.  It will be a no-op in case it was already using that array, but otherwise it would involve a copy.

**Comment by YohannDudouit** [comment]
I'm not a fan of GPU backend working with CPU `Vector`, to me it would be cleaner to have an `CeedEquate(CeedVector in, CeedVector out)` method where the vector you use with the GPU backend is a GPU vector.
```
  CeedVectorSetArray(host_xceed, CEED_MEM_HOST, CEED_USE_POINTER, h_x);
  CeedVectorSetArray(device_xceed, CEED_MEM_DEVICE, CEED_USE_POINTER, d_x);
  CeedVectorEquate(host_xceed, device_xceed);
  CeedVectorSetArray(host_yceed, CEED_MEM_HOST, CEED_USE_POINTER, h_y);
  CeedVectorSetArray(device_yceed, CEED_MEM_DEVICE, CEED_USE_POINTER, d_y);

  CeedOperatorApply(op, device_xceed, device_yceed,
                    CEED_REQUEST_IMMEDIATE);
  CeedVectorEquate(device_yceed, host_yceed);
```

**Comment by jeremylt** [comment]
I don't think there is such a thing a 'CPU vector. There is a location where the data originated, but after the user provides the data via CeedVectorSet, the backend gets to decide if that data needs to move frome CPU to GPU or GPU to CPU or not at all. 

 I really don't think we want to make the user create two copies of every vector. The user shouldn't be managing backend decisions about data location. The backend gets to choose when to move data, unless the user needs the original location they provided, in which case this new function would be called.

**Comment by jedbrown** [comment]
In this example, you would be using two different `Ceed`s on different
devices and somehow they would know how to communicate with each other?
How do you write a single user source that runs with any CEED resource?

**Comment by YohannDudouit** [comment]
So if I understand you correctly when you do:
```CeedVectorSetArray(user->xceed, CEED_MEM_HOST, CEED_USE_POINTER, x);```
if the backend is a GPU backend, then the `user->xceed` copies the data from the host memory `x` to the GPU memory `user->xceed->data`?
So when you do `CeedVectorSync(user->xceed)` where is the backend supposed to put the data on host since the `data` is a GPU pointer?

**Comment by jeremylt** [comment]
I think we view CeedVectors slightly differently:

`CeedVectorSetArray(CeedVector vec, CeedMemType mtype, CeedCopyMode cmode, CeedScalar *array)`:
  This command tells the backend where to find the data for this vector, not where to store the data during computation.

`CeedVectorGetArray(CeedVector vec, CeedMemType mtype, CeedScalar **array)`:
  This command tells the backend to provide a mtype pointer to the data contained in the CeedVector, but the user is indicating that they will mutate the data at this memory location. A copy from device would be required if the user requests a host pointer.`CeedVectorRestoreArray()` is required to let the backend know that the data modification is complete and to set the vector to the modified values.

`CeedVectorGetArrayRead(CeedVector vec, CeedMemType mtype, CeedScalar **array)`:
  This command tells the backend to provide a mtype pointer to the data contained in the CeedVector, but the user is indicating that they will not mutate the data at this memory location. A copy from device would be required if the user requests a host pointer.

`CeedVectorSync(CeedVector vec)`:
  This proposed command would tell the backend to update the memory location last provided in `CeedVectorSetArray()` but that the user does not want the backend to incorporate any changes made at this memory location, for instance because this is an output vector. This would only make sense in the context of `CEED_USE_POINTER` or `CEED_OWN_POINTER`. In this case it would not make sense to use 'CeedVectorGetArrayRead()' because this command is an indication that the data will not be mutated, which is not necessarily the case with 'CeedVectorSync()'.

**Comment by jeremylt** [comment]
> I think I got it, when you do `CeedVectorSetArray(user->xceed, CEED_MEM_HOST, CEED_USE_POINTER, x);` with a GPU backend, you copy from host memory `x` to whatever in your backend `CeedVector` **and** you store a reference to the source pointer `x`. So when you do `CeedVectorSync(user->xceed)`, you update the host memory pointer reference `x` with the GPU data?

Exactly

**Comment by YohannDudouit** [comment]
Thank you for your patience and detailed explanation, I got indeed influenced by the work I'm doing in MFEM and got lost... I still favour a design where things are more explicit though, like
`CeedVectorSync(CeedVector vec, CeedMemType mtype, CeedScalar* array)`
where you explicitly say where you want the values to be copied to, we might want to omit the `mtype` argument since we could always assume that it is equal to `CEED_MEM_HOST`, but I feel that it could be useful to allow the synchronisation to go both ways (not only GPU to HOST). I guess that your concern with this design is that we might not know at the time we call `CeedVectSync` that it should go to `x`...

**Comment by jedbrown** [comment]
The issue is that we want this to be a no-op when it can be.  If you provide a destination array, then it always means a copy.

**Comment by YohannDudouit** [comment]
Why comparing pointer address wouldn't work? Is it too expensive?

**Comment by jeremylt** [comment]
My concern is that we need to be careful on documentation of this function. It should be clear in the documentation (and possibly the name) that the user gets mutatable access to the data but does not expect libCEED to use these modifications. 

In my head, get/restore is libCEED giving the user access to modify our arrays whereas set/sync is the user giving libCEED access to modify their arrays.

**Comment by jedbrown** [comment]
Oh, I see what you mean.  It just seems excessively low level because that pointer might be inside an application Vector object that was set up to be able to exchange its array with the CeedVector.

**Comment by YohannDudouit** [comment]
I see a potential problem if you initialize your vector with a device memory pointer (`CeedVectorSetArray(xceed, CEED_MEM_DEVICE, CEED_USE_POINTER, x)`). Does that mean that you have to `CeedVectorSync(xceed)` and then do the *real* synchronization manually because the `CeedVectorSync` didn't synchronize anything? (by synchronizing I mean moving the data from the GPU to the HOST)
It sounds like a non instinctive behaviour to me.

**Comment by jeremylt** [comment]
We could 
a) Allow this and intend this function to sync the last set pointer regardless of host vs device
b) Have backends error if no host pointer has been set

**Comment by YohannDudouit** [comment]
- I guess it also assumes that you always know when you do `CeedVectorSync(xceed)` what the last pointer was and where it was, is it reasonable?
- I also find that setting the pointer with `CeedVectorSetArray` to a HOST pointer before doing `CeedVectorSync` is unnatural, especially since the documentation of `CeedVectorSetArray` says "freeing any previously allocated array if applicable" which could result in an undesired behaviour.
- I am also confused by what you two are saying. If according to @jedbrown there can be no-op it means that the backend is directly using the pointer for the computation, thus calling `CeedVectorSync` is indeed no-op, but the mutable access to the pointer **has** impact to future computations with the `CeedVector`. However, if the backend uses its own pointer (might be because it's a GPU backend), then `CeedVectorSync` implies a copy, but the mutable access to the pointer **does not** impact future computations with the `CeedVector`. If I'm correct, this means that the behaviour of a code could change with the backend used, I don't think that we want this kind of behaviour due to the complex bugs this might create. Does that mean that `CeedVectorSync` should be coupled with some safety functions in order to guaranty that the behaviour of the code doesn't change from one backend to the other? It feels like we might run in some ownership issues, where we loose track of who is modifying what.

**Comment by jedbrown** [comment]
`CeedVectorSync` should not specify HOST versus DEVICE. It would only mean that whatever memory has been provided to the Vector should be updated. That means if you provide a device pointer to a backend that opts not to use device memory for the operation (conceivable for sizes that are too small to pay off the latency), then the device array would be updated.

If the memory is updated, the user can call `CeedVectorSetArray` with the array that is already used (implementation would need to be updated to early return in that case) to ensure that other copies (if they exist) have been invalidated.

Note that users can alternatively use `CeedVectorGetArray` and `CeedVectorGetArrayRead` with `CEED_MEM_DEVICE` as appropriate to perform in-place operations. Most users should probably do that, but it is messy for Fortran77 and certainly a problem for a package that statically allocates globals and is hard-coded to use them.

**Comment by YohannDudouit** [comment]
> We need to add a new frontend function CeedVectorSyncArray to signal to GPU backends that CeedVector data needs to be pushed to the host.

I don't think that this is the specification that you have in mind.
I'm not against what you propose but I'm not completely sure that this is what @jeremylt initially proposed.
So if I understand what you propose, when you want to update the given pointer, what you do is:
```
  CeedVectorSetArray(user->xceed, CEED_MEM_HOST, CEED_USE_POINTER, x);
  CeedVectorSetArray(user->yceed, CEED_MEM_DEVICE, CEED_USE_POINTER, y);

  CeedOperatorApply(user->op, user->xceed, user->yceed,
                    CEED_REQUEST_IMMEDIATE);
  CeedVectorSync(user->yceed); // Synchronise y with yceed->data
  ...
  CeedVectorSetArray(user->yceed, CEED_MEM_DEVICE, CEED_USE_POINTER, y); // Forces to use y, and get rid of any outdated copies of y
  ...
  CeedVectorGetArrayRead(user->yceed, CEED_MEM_HOST, read_y);
  // use read_y for printing results for instance
```
I'm still a bit scared that we might end up doing unneeded `CeedVectorSync` just for safety in cases where the `CeedVector` was initialized by someone else, but I guess we can't really avoid this and it looks like the best solution.

**Comment by jeremylt** [comment]
Yeah, I think my initial wording was not sufficiently general.

Updated wording: We need to add a new frontend function `CeedVectorSyncArray` to signal to backends that the memory at the location last provided by `CeedVectorSetArray` needs to be updated with the most up to date data in the CeedVector. In the case of `CeedVectorSetArray` last being called with `CEED_COPY_VALUES`, this function should return an error. In the case that the memory location is already up to date, this function should return a success with no additional data movement.

Is this zeroing in on it?

**Comment by YohannDudouit** [comment]
I would think that with `VectorGetArray` and `VectorRestoreArray` the `VectorSyncArray` shouldn't be required any more, what am I missing? To me `CeedVectorSyncArray` is pretty much equivalent to `VectorGetArray` or `VectorGetArrayRead` unless the software using libCEED is not respecting libCEED memory model and is not accessing the `Vector` array each time through `VectorGetArray` but with a stored pointer.

**Comment by jeremylt** [comment]
SyncArray is for when libCEED has been handed access to an array of a parent program, such a PETSc or Nek5k. In this sort of workflow, SetArray would be called to direct libCEED to use the data provided by the parent program and then SyncArray would be called to direct libCEED to ensure that the provided memory location is up to date so that the parent program can use the array again.

**Comment by jedbrown** [comment]
Perhaps this should be an interface that takes exclusive access and ownership of the array, something like VectorTakeArray(), instead of an action-at-a-distance interface VectorSyncArray that can't be reasoned about locally?

**Comment by YohannDudouit** [comment]
The thing that I don't understand is that `SyncArray` has to be in the parent program right? So why the parent program shouldn't use `GetArray`, `RestoreArray`? Even if he gave the pointer in the first place, libCeed memory model should require the parent program to use the same memory model we use, no? That would mean that if the parent programs modifies the array between calls to `OperatorApply`, then the work-flow in the parent program should be something like:
```
CeedVectorRestoreArray(in, arrayIn);
CeedVectorRestoreArray(out, arrayOut);
CeedOperatorApply(op, in, out, request);
CeedVectorGetArray(in, mtype, arrayIn);
CeedVectorGetArray(out, mtype, arrayOut);
```
Thus, we could set `array` to `NULL`  when `CeedVectorSetArray(vec, mtype, CEED_USE_POINTER, &array)` is called, that would force the parent program to use `CeedVectorGetArray/CeedVectorGetArrayRead`.
Changing a bit the signature of `SetArray` but making the memory model a bit safer.

**Comment by jedbrown** [comment]
The issue is ownership. If a caller allocates the memory, it's natural to expect

    use_array(array);
    call_libceed_using_array(array);
    use_array_again(array);

Indeed, we can't prevent this sort of code except by insisting that our interface has undefined behavior in that case. Mandating that the caller use `CeedVectorGetArray` places libCEED at the center of control even if the caller desires a library that uses (no-copy) some data from the caller. I'm not sure the semantics need to be different, but I do think callers that retain ownership and wish for libCEED's relationship with the array to be ephemeral would prefer to "take back" the array, such that no libCEED objects retain a reference. In that case, a caller would use `CeedVectorSetArray` and an inverse operation that ensures that the array contents are current and drops its reference.

**Comment by YohannDudouit** [comment]
Working with @jeremylt on making the Cuda backend work with the PETSc examples, we realized  that we might need to synchronize passive output vectors, which might be impossible in certain conditions with the proposed interface. A solution could be to use something like `CeedOperatorSyncOutput(char* name)`.

**Comment by jedbrown** [comment]
Seems to me it would still be a `CeedVector` method, but we might need an accessor to named fields `CeedOperatorGetField(op, "fieldname", &vec)` in case the user loses the Vector whose array they are about to access.

**Comment by jeremylt** [comment]
I can see `CeedOperatorGetField(op, "fieldname", &vec)` being desirable on its own and for `CeedVecSyncArray`.

**Comment by YohannDudouit** [comment]
I agree that this looks like the right choice.
Just a precision on `CeedVectorSyncArray`, do the synchronization goes both ways, or does the vector remembers how it was initialized (by `CEED_MEM_HOST` or `CEED_MEM_DEVICE`) and only update one way when necessary? (In order to avoid unnecessary synchronizations) Or if we want a less abscure behaviour we could imagine a `CeedMemType` being part of `CeedVectorSyncArray` to avoid unnecessary synchronizations.

**Comment by jedbrown** [comment]
I'm cycling back to whether we should just use `CeedVectorGetArray`, perhaps allowing `CeedVectorGetArray(vec, CEED_MEM_DEVICE, NULL)` which would mean "I know what memory that is because I'm the one who gave it to you. Now I need it to be current and I intend to modify it."

In that scenario, if you didn't need it to be current, you could just modify the state at that memory and call `CeedVectorSetArray` again to notify the vector that it has been modified.

How does that sound?

**Comment by YohannDudouit** [comment]
I tend to think that interfaces using `NULL` as special case lead to really bad design. I personally think that `NULL` should be avoided as much as possible in C, and at all cost in C++ (and the guy who introduced it too: https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare). Subverting the typing system for convenience is an error I think.

**Comment by jedbrown** [comment]
There's a difference between returning `NULL` when the caller would usually expect a valid pointer (we don't do that) and using `NULL` to implement optional arguments as a way to avoid the code and documentation duplication of having separate functions. Regardless, we could just keep the current interface (without allowing `NULL`) in which case the caller would use `CeedVectorGetArray` with a dummy variable in such instances.

**Comment by YohannDudouit** [comment]
I agree that using `NULL` to implement optional arguments is not as bad as returning `NULL`, I still think it's a bad design choice though (more difficult to avoid in C because of the absence of overloading).
I also agree that the dummy pointer feels artificial, that's why I think that @jeremylt 's proposition is the nicest:
```c
int CeedVectorSyncArray(CeedVector v, CeedMemType mem) {
  const CeedScalar *array;
  CeedVectorGetArrayRead(v, mem, &array);
  CeedVectorRestoreArrayRead(v, &array);
  return 0;
}
```
However, I think that @jeremylt wants to get rid of the `mem` argument, which drives us to my previous comment. If we get rid of the `mem` argument, should the `CeedVector` know with what `CeedMemType` the function `CeedVectorSetArray` was used (to only make sure that this memory is sync not both), or should it synchronize both host and device regardless (which I think suboptimal). I personally think there is some benefit in keeping the `mem` argument. leading to the following implementations:
- option 1:
```c
int CeedVectorSyncArray(CeedVector v) {
  CeedMemType mem;
  CeedVectorGetInitMemType(v, &mem); // new function
  const CeedScalar *array;
  CeedVectorGetArrayRead(v, mem, &array);
  CeedVectorRestoreArrayRead(v, &array);
  return 0;
}
```
- option 2:
```c
int CeedVectorSyncArray(CeedVector v, CeedMemType mem) {
  const CeedScalar *array;
  CeedVectorGetArrayRead(v, CEED_MEM_HOST, &array);
  CeedVectorRestoreArrayRead(v, &array);
  CeedVectorGetArrayRead(v, CEED_MEM_DEVICE, &array);
  CeedVectorRestoreArrayRead(v, &array);
  return 0;
}
```

**Comment by jeremylt** [comment]
See PR #214
