### ISSUE TITLE
Feasibility of implementation of operators with by-element varying components

### ISSUE THREAD

**Issue by eliasboegel** [CEED/libCEED#1662]
Hi - it's me again,

I have a special use-case that I'm wondering if it could be made to work with current libCEED, and if not, if support for it could feasibly be implemented in a reasonably efficient fashion.

I would like to compute the action of a vector mass operator with matrix coefficient:
```math
\int_\Omega \boldsymbol{R}\boldsymbol{u} \cdot \boldsymbol{v}\ d\Omega
```

My special need is that I would like to allow the number of components of $\boldsymbol{u}$ (and the size of the coefficient matrix $\boldsymbol{R}$ as well as the number of components of the vector test function $\boldsymbol{v}$) to change per element.

My understanding is that none of the element restrictions and by extension none of the backends in libCEED allow this. The closest I see are the AtPoints functions, which at first glance seem to allow a different number of points (but not components) per element. Is this right?

Do you any theoretical roadblocks in performing this kind of operation efficiently with a varying number of components on accelerators? In my case, the DOFs can be quite dense, reaching >1000 DOFs per quadrature point relatively quickly.

I would love to hear your opinions.

**Comment by jeremylt** [comment]
AtPoints is not very efficient for devices, so I assume some naive implementation of allowing variable numbers of components would be a problem too. 

Would it be reasonable to batch elements instead and use separate restrictions and bases for homogeneous batches?

**Comment by eliasboegel** [comment]
Thanks Jeremy! I assume this would mean restricting myself to a few discrete steps in component number? Not ideal, but it could work reasonably well in my case.

Do you mind elaborating on why AtPoint turns out to be inefficient on device for my understanding? My assumption at the moment is that a variable number of point/components, be it number of points or number of components, would prevent unrolling any one of the loops in the kernels. Is that right?

**Comment by jeremylt** [comment]
The rule of thumb I understand is that the GPU is most efficient when all of its threads are doing the same thing. With the AtPoints case we get there by padding out each element to contain the same number of points by replication of the last point in elements that have fewer points and compiling the kernels to that size. That costs us some extra work and memory but keeps all of our memory access patterns the same and gives us compile time constant loop bounds. We also lose the tensor product structure that we see with a standard quadrature space, so we lose efficiency because of that too.

Given the structure of the work vectors used by our GPU backends, the memory access would seem to be the particularly tricky part to overcome with variable numbers of components, as the q vectors are contiguous by components. The trick of padding out feels like it would quickly consume an unreasonable amount of memory.

**Comment by eliasboegel** [comment]
I see. Padding would certainly be unrealistic in my case since ideally the component count would vary by 2 or 3 orders of magnitude. The waste would be enormous. The tensor product structure would remain in my case. How big is the impact of constant loop bounds compared to a runtime loop construct on device? 

When you say "contiguous by components", you mean that the Q vector stores all DOFs associated with a component in contiguous fashion? For me, the opposite would be desired, i. e. keeping DOFs contiguous by point. Is this possible with current implementations, and if not, could that fit into the structure of libCEED?

**Comment by jeremylt** [comment]
A fixed number of components is set at basis kernel compile time so it's hard to assess. I could try hacking in a runtime selection of a uniform number of components used for every single element. I would guess it is a fairly large performance hit.

---

One goal of the GPU backends is to launch as few kernels as possible. To that end, each operator processes all elements and quadrature points all at the same time. In order to do this, the data is ordered by [point in element, element, component]. This ordering on the GPU is a byproduct of how QFunctions index into the input data, but how QFunctions index also helps our tensor contractions on the CPU.

The ability of backends to pick their data ordering is pretty important to the design of libCEED so I don't see an easy way to take that out.

---

We usually tackle heterogeneity to this degree by setting up separate operators of more uniform subproblems. 

I see two things in this discussion here
1) different numbers of solution components on elements in the mesh
2) different numbers of coefficients at each quadrature point

Without having deep knowledge of the first problem, my instinct would be 
1) group elements by the number of components into separate sub operators
2) group elements by the maximum amount of coefficients needed for a quadrature points in that element into separate sub operators 

Unfortunately that would lead to combinatorial growth in the number of sub operators if there is a very large amount of variation. I don't have a particular answer here, more trying to explore the issue here.

**Comment by jeremylt** [comment]
> Can you confirm that the data is ordered in a way of say: [...., pt0el0comp0, pt0el0comp1, pt0el0comp2, ....]?

No, that's backwards from what I was trying to explain.

[qpt0el0comp0, qpt1el0comp0, qpt2el0comp0, ..., qpt0el1comp0, qpt1el1comp0, qpt2el1comp0, ..., qpt0el2comp0, qpt1el2comp0, qpt2el2comp0, ..., qpt0el0comp1, qpt1el0comp1, qpt2el0comp1, ...]

All of the comp0, comp1, etc data is contiguous.

For externally computed data, the user needs to provide both a pointer to a CeedVector via CEED_USE_POINTER and an CeedElemRestriction that describes how to index into the data. The backend then uses the CeedElemRestriction to make a permuted copy as needed to get the best performance.

**Comment by eliasboegel** [comment]
Thanks a lot so far! I will probably have more questions down the line. Do you prefer that I open issues as I've done so far, or do you prefer a different way of reaching out about things that are more libCEED usage than issues.

**Comment by jeremylt** [comment]
Issues work fine for me. 

I'm still pondering if there's a better way to handle the heterogeneity you described above, but no strokes of genius yet :)

**Comment by eliasboegel** [comment]
Sounds good. I will also have a look at the operation I would like to perform and see if I can find a (libCEED or not) way of mapping it to a GPU in a reasonable way.

**Comment by jedbrown** [comment]
Note that the ordering (with the innermost index over points, which may span a batch of elements) is due to memory coalescing and the way SIMT vectorizes, as well as the way CPU SIMD instructions work. If you change it, the compiler and hardware would have to do lots of transposition, and in many cases would result in quite poor code.

I think you should try binning with padding. Perhaps start with powers of 2 number of components, then profile to see how big those bins are and thus how much can be gained by a different binning strategy. I think any custom strategy would amount to a finer-grained version of this type of binning, but I'm skeptical that writing a more sophisticated kernel in which different thread blocks of the same kernel process different size elements will have a performance benefit compared to separate kernel launches (perhaps on different threads so they can run concurrently).

Issues or Discussions are fine for this sort of dialog.

**Comment by eliasboegel** [comment]
Awesome, thanks Jed.
I think the binning is a good strategy for now and will be good enough - thank you to both of you for this suggestion. If that still doesn't cut it down the line then I'll think about it again. Thanks for the, as always, quick help!

**Comment by eliasboegel** [comment]
> > Can you confirm that the data is ordered in a way of say: [...., pt0el0comp0, pt0el0comp1, pt0el0comp2, ....]?
> 
> No, that's backwards from what I was trying to explain. Shoulda started with a diagram like you have
> 
> ```
> [qpt0el0comp0, qpt1el0comp0, qpt2el0comp0, ..., qpt0el1comp0, qpt1el1comp0, qpt2el1comp0, ..., qpt0el2comp0, qpt1el2comp0, qpt2el2comp0, ..., qpt0el0comp1, qpt1el0comp1, qpt2el0comp1, ...]
> ```
> 
> All of the `comp0`, `comp1`, etc data is contiguous.
> 
> For externally computed data, the user needs to provide both a pointer to a `CeedVector` via `CEED_USE_POINTER` and an `CeedElemRestriction` that describes how to index into the data. The backend then uses the `CeedElemRestriction` to make a permuted copy as needed to get the best performance.
> 
> If the same libCEED backend is used to create the data, you can create a `CeedElemRestriction` that has `CEED_STRIDES_BACKEND` and then there is no extra copying.

Brief follow-up on this:
The documentation tells me that, unless I create my own external array and let a libceed Vector use this memory I allocated externally, the ordering of a libceed Vector is backend-dependent. So far so good. Now, two things:
1. In this comment you give a "fixed" ordering
2. In the vector mass example (in this case the Rust version), a solution vector is initialized with the component index, but this initialization assumes the ordering

To which extent can I rely on this ordering? If my data is touched by different backends, would it always be better to allocate data externally and define an ordering myself at the expense of additional copies that may or may not be redundant depending on the backend?

**Comment by jedbrown** [comment]
Why do you need to pass data between different backends? (Maybe there's a better way to meet your needs.) If you need to use a non-native ordering, you'll have to specify it. Not sure if that's what you're looking for.

**Comment by eliasboegel** [comment]
My thinking in that use-case would be when data that was created by one backend is saved to disk in the same order as in-memory and loaded in that same order for use with another, say in a simple checkpoint system.

**Comment by jedbrown** [comment]
I would always put in a specified ordering when saving to disk, rather than relying on implicit matching or attaching metadata to reconstruct a specific backend ordering.

**Comment by eliasboegel** [comment]
Thanks!

**Comment by jeremylt** [comment]
Just to add a bit more info

1. The ordering I gave above is the q vector ordering used by the GPU backends. The CPU backends use a different ordering.

2. The ordering of a local vector and the q vector are generally independent, unless you use `CEED_STRIDES_BACKEND` for a vector that was an output from a CeedOperator

if you use `CEED_STRIDES_BACKEND` then you cannot expect that data to be compatible between backends. In practice, you can reasonably assume all `/cpu/self/*` use the same q vector ordering and `/gpu/cuda/*` all use the same, different q vector ordering. Like Jed said, for a situation where you want I prescribed local vector ordering, I would avoid `CEED_STRIDES_BACKEND` or remap from `CEED_STRIDES_BACKEND` to a prescribed ordering via a CeedOperator.

**Comment by eliasboegel** [comment]
Thanks for the information!
I have another question related to the element restrictions for the batched approach to the variable component requirement of this issue.

I will need several different element restrictions, one for each batch. I normally would use CeedElemRestrictionCreateStrided for DG methods as there are no shared DOFs between elements, however I do not see a way to use a strided restriction given that all but one batch operate on a part of the lvector not starting at index 0.
Example: Assume 2 elements split two batches as [el0batch0, el1batch1]. A strided restriction (to my understanding) starts indexing at index 0 in any case, so I will not be able to create a strided restriction to the DOFs of el1 only - is this correct?

I assume the correct way to do this is to use CeedElemRestrictionCreate only, with appropriate offsets, even without shared DOFs?

Thanks for all the help and your patience! I appreciate it.

**Comment by jeremylt** [comment]
Is each batch contiguous in memory? If no, then I think a `CeedElemRestrictionCreate` would be the only way to go

**Comment by eliasboegel** [comment]
Batches are not contiguous, since an element's assigned batch may change and keeping them contiguous would require sorting and permuting DOFs every time that happens. I will go with CeedElemRestrictionCreate - thanks!
