### ISSUE TITLE
Make libCeed compatible with multiple devices.

### ISSUE THREAD

**Issue by YohannDudouit** [CEED/libCEED#194]
So far I have always allocated the device 0 to the GPU backend, but I think that using multiple devices on a node will soon become important. I think we should start thinking about how this kind of things will be specified. Maybe that the `spec` for a backend should include the device identity, _e.g._ `/gpu/cuda/deviceId` where `0` is the default one when `deviceId` is not provided.

**Comment by jedbrown** [comment]
Yes, I think we talked about this in the abstract sometime last year. Since libCEED is not aware of its environment, it'll be up to the caller to create resource identifiers for multi-device nodes (rather than passing the same user-provided resource to every `CeedInit`).  Code such as the following may be useful.

    MPI_Comm_split_type(comm, MPI_COMM_TYPE_SHARED, ..., &nodecomm);
    MPI_Comm_rank(nodecomm, &noderank);

**Comment by jedbrown** [comment]
I'll close this unless you think there is something that libCEED can and should do itself (without making it depend on MPI). Feel free to reopen.
