### ISSUE TITLE
Create gallery of QFunctions (mass, Laplace, etc.)

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#37]
Public interface something like

```c
int CeedQFunctionCreateFromGallery(Ceed ceed, const char *spec, CeedQFunction *qf);
```

where `spec` is something like `"Mass"` or `"Mass:dim=3,rho=10"`. (Many possible syntax choices for options.)

**Comment by jedbrown** [comment]
Like all libCEED objects, each `QFunction` instance is specific to the given `Ceed`. The Gallery code should execute for any backend. If a backend provides a specialized implementation, that will be bundled with the backend, not with the Gallery.

A `CeedOperator` is not complete until its fields have been specified. I'd prefer for the Gallery to return a "complete" `QFunction` instead of a partly created `Operator`, but I suppose a convenience function could be created so the user would need to see one fewer objects.

**Comment by jeremylt** [comment]
In my mind, a single call of `CeedQfunctionCreateFromGallery(ceed, "Mass")` would replace lines 349-353 of the PETSc `bp1.c` file, and the QFunction would not need to be given as it is in the `bp1.h` file.

We couldn't do this completely at the CeedOperator level because we don't know the user basis, restriction, vectors, etc in advance, so the user would still need to set that information.

**Comment by YohannDudouit** [comment]
I am currently working on integrating libParanumal in libCEED, but there is still some obscure corners in the way it will interact with the `QFunctionGallery`.
From libParanumal side I get the operator (`CeedOperator` level) doing something like:
```cpp
mesh->device.buildKernel(fileName, kernelName, kernelInfo);
```
But I cannot make this function call at the moment where I call `CeedQFunctionCreateFromGallery(ceed, opName, qf)` since `mesh` and `kernelInfo` need information at `CeedOperator` level to create the kernel.
So, does that mean that I should put all the information in the `void* data` of the `CeedQFunction_private` when calling `CeedQFunctionCreateFromGallery(ceed, opName, qf)` (`qf->data` would contain just the `opName`)? And then I extract the information (`opName`) contained in `data` and use it when calling `CeedOperatorCreate(ceed, qf, NULL, NULL, op)`, and from the information of `ceed` and `opName` I create the libParanumal `mesh` and `kernelInfo` and then call `mesh->device.builKernel(...)` to create the libParanumal operator?
Is it what you had in mind @jedbrown and @jeremylt ?

**Comment by jeremylt** [comment]
It is up to the specific backends how they use the data field; that seems like a reasonable usage to me.

You may want to look into the delegate ceed functionality. You shouldn't have to duplicate all of the code for whatever backend you are basing the libParanumal backend off of (I am curious if you using OCCA or the half abandoned Cuda work). You can set a delegate and then any functions you don't overwrite are uspplied by the delegate. You can see an example of this by looking at the blocked backend vs the ref backend.

In my perfect world, the libparanumal backend would pass any QFunction it does not have a kernel for off to its delegate (OCCA or Cuda).

**Comment by YohannDudouit** [comment]
If `CeedQFunctionCreateFromGallery` initializes the fields, don't we need to also provide some kind of `void* qFunctionData` that we would have to standardize for each `qfName` to initialize correctly the `qFunction`:
```cpp
CeedQFunctionCreateFromGallery(ceed, qfName, qfData, qf);
```
?
I have a hard time seeing how that would work though, do we want to define a standard structure for the initialization of each `QFunction` in the gallery?
```c
CeedQFunctionCreateFromGallery(Ceed ceed, char* qfName, void* qfData, CeedQFunction qf){
  switch(qfName){//pseudo-code
    case "Mass":
      //Are we supposed to initialize some kind of default implementation of qf here?
      CeedCreateDefaultMassQFunction(ceed, (CeedMassQData)qfData, qf);
      //The following is specific to libParanumal, so I guess this should go somewhere else, but where?
      QFunctionData_libParanumal data = {qfName, qfData};
      qf->data = (void*)data;
      return 0;
    ...
    default:
      ceed_error("This QFunction does not belong to the gallery");
      return 1;
  }
}
```
Where would these `QFunctionGallery` data structures be described in a convenient way?
Does what you had in mind to use the Gallery is something like:
```c
  CeedMassQData data_mass = {...};
  CeedQFunctionCreateFromGallery(ceed, "Mass", (void*)data_mass, qf_mass);
  CeedOperatorCreate(ceed, qf_mass, NULL, NULL, &op_mass);
  CeedOperatorSetField(op_mass, "u", Erestrictu, basisu, CEED_VECTOR_ACTIVE);
  CeedOperatorSetField(op_mass, "rho", Erestrictui,
                       CEED_BASIS_COLOCATED, rho);
  CeedOperatorSetField(op_mass, "target", Erestrictui,
                       CEED_BASIS_COLOCATED, target);
  CeedOperatorSetField(op_mass, "v", Erestrictu, basisu, CEED_VECTOR_ACTIVE);
```
I can't see when I have the opportunity to create the libParanumal `mesh` and `kernelInfo`, and call `mesh->device.buildKernel(fileName, kernelName, kernelInfo)`.

I think I missed a step with the delegate functionality. Can you elaborate a little bit please? Do you refer to the capability to use implementation from another backend? Is it for the `vec` functionalities, since the rest does not exist in the libParanumal backend? Or is it to default another backend for unsupported `QFunction`?

PS: I am planning to resurrect the Cuda backend, using the String approach described in #164

**Comment by jedbrown** [comment]
What is the `data_mass` that you have in mind? Any field-like inputs should come through the fields as shown above. Anything backend-specific comes via the backend creation function just like everything else.

**Comment by jeremylt** [comment]
mesh->device.buildKernel(fileName, kernelName, kernelInfo) would probably show up in the first run of CeedOperatorApply_libpara I'd imagine. Backend specific activities should be in the backend functions. 

The delegate functionality can be used in two ways. First, if a backend does not give an implementation of a function, such as CeedVectorCreate, then the implementation provided by the delegate is used. Second, which hasn't been used in libCEED yet, is that a backend can selectively dispatch to a delegate.

**Comment by YohannDudouit** [comment]
@jedbrown I guess we at least need the dimension, so that we can do:
```c
  CeedQFunctionAddInput(qf_setup, "x", mass_data->dim, CEED_EVAL_INTERP);
  CeedQFunctionAddInput(qf_setup, "dx", mass_data->dim, CEED_EVAL_GRAD);
  CeedQFunctionAddInput(qf_setup, "weight", 1, CEED_EVAL_WEIGHT);
  CeedQFunctionAddOutput(qf_setup, "rho", 1, CEED_EVAL_NONE);
  CeedQFunctionAddOutput(qf_setup, "true_soln", 1, CEED_EVAL_NONE);
  CeedQFunctionAddOutput(qf_setup, "rhs", 1, CEED_EVAL_INTERP);
```
We could also imagine `qfName=SetupMass3d` in order to remove the `qfData` if we never need more information at this point than the dimension of the problem.
```c
int CeedQFunctionCreateFromGallery(Ceed ceed, QFunctionName qfName, CeedQFunction *qf){
CeedInt dim = 0;
switch(qfName){
  case SetupMass3d:
    dim++;
  case SetupMass2d:
    dim++;
  case SetupMass1d:
    dim++;
    //What would be DefaultMassSetup? CPU only?
    CeedQFunctionCreateInterior(ceed, 1, DefaultMassSetup, __FILE__ ":DefaultMassSetup", qf);
    CeedQFunctionAddInput(*qf, "x", dim, CEED_EVAL_INTERP);
    CeedQFunctionAddInput(*qf, "dx", dim, CEED_EVAL_GRAD);
    CeedQFunctionAddInput(*qf, "weight", 1, CEED_EVAL_WEIGHT);
    CeedQFunctionAddOutput(*qf, "rho", 1, CEED_EVAL_NONE);
    CeedQFunctionAddOutput(*qf, "true_soln", 1, CEED_EVAL_NONE);
    CeedQFunctionAddOutput(*qf, "rhs", 1, CEED_EVAL_INTERP);
    return 0;
  case Mass:
    //What would be DefaultMass? CPU only?
    CeedQFunctionCreateInterior(ceed, 1, DefaultMass, __FILE__ ":DefaultMass", qf);
    CeedQFunctionAddInput(*qf, "u", 1, CEED_EVAL_INTERP);
    CeedQFunctionAddInput(*qf, "rho", 1, CEED_EVAL_NONE);
    CeedQFunctionAddOutput(*qf, "v", 1, CEED_EVAL_INTERP);
    return 0;
    ...
}
return 1;
}
```
where `QFunctionName` is an enumerated type instead of a `char*` (I think this is more convenient and safer).
- Is it the kind of `QFunctionGallery` you had in mind?
- Where do I put the backend specific information in this function? Should `QFunction` contain `QFunctionName`?

@jeremylt Thank you for this simple solution, for some reason I didn't think about it.

In terms of work organization, would you prefer if I first propose a draft of the `QFunctionGallery` in a PR and then integrate libParanumal in another PR in order to have more atomic PRs, or is it okay to do both at the same time so that I can better see the implications of one PR on the other?

**Comment by YohannDudouit** [comment]
@jedbrown I realized you had initially foreseen a `spec` instead of a `qFunctionName`. I guess my proposition of `qFunctionName`+`qFunctionData` is equivalent to the `spec`. I am not a big fan of the `spec` though since it implies to write some kind of parser, if I'm correct.

**Comment by jeremylt** [comment]
See #311.
