### ISSUE TITLE
libCEED using Hiprtc

### ISSUE THREAD

**Issue by YohannDudouit** [CEED/libCEED#449]
It seems that Hip has JIT compilation now, the interface seems to be the same as nvrtc, thus it should be straightforward to port Cuda backends to Hip.
https://github.com/ROCm-Developer-Tools/HIP/blob/master/include/hip/hcc_detail/hiprtc.h

**Comment by jedbrown** [comment]
Yes, this file has actually been there [since May](https://github.com/ROCm-Developer-Tools/HIP/pull/1097), but it still [isn't documented](https://rocm-documentation.readthedocs.io/en/latest/search.html?q=hiprtc&check_keywords=yes&area=default) so I don't know how to interpret it. We talked with @noelchalmers and Damon at CEED3AM and they didn't seem to think it was operational yet. I'd recommend testing a simple case before investing significant time porting to an interface that may or may not work.
