### ISSUE TITLE
PETSc BPs with tetrahedral elements

### ISSUE THREAD

**Issue by jedbrown** [CEED/libCEED#454]
DMPlex can read/create non-tensor meshes (see the `simplex` argument to `DMPlexCreateBoxMesh()`). `PetscFEGetCellTabulation()` will return the (non-tensor) tabulated basis matrices.

We should add to `examples/petsc/bps.c`:
1. Add a run-time flag to pass the non-tensor representation to libCEED. This is just to measure how much we'd give up if we weren't exploiting the tensor product. I think this will sometimes be useful for comparisons, but we'll likely never want it in practice (beyond first order).
2. Add `-simplex` to use a simplicial mesh.

**Comment by valeriabarra** [comment]
Yes, I agree that this is a good idea. I have [used it](https://github.com/CEED/libCEED/blob/3d95b2618b5621c86c9a8dad43d4c78791e053e9/examples/petsc/bpssphere.c#L116) in my `valeria/bps-on-a-sphere` branch and I think I also had it in my area example at some point (not anymore though).

**Comment by jeremylt** [comment]
With

```
CEED_EXTERN int CeedBasisGetQRef(CeedBasis basis, const CeedScalar **qref);
CEED_EXTERN int CeedBasisGetQWeights(CeedBasis basis,
                                     const CeedScalar **qweight);
CEED_EXTERN int CeedBasisGetInterp(CeedBasis basis, const CeedScalar **interp);
CEED_EXTERN int CeedBasisGetInterp1D(CeedBasis basis,
                                     const CeedScalar **interp1d);
CEED_EXTERN int CeedBasisGetGrad(CeedBasis basis, const CeedScalar **grad);
CEED_EXTERN int CeedBasisGetGrad1D(CeedBasis basis, const CeedScalar **grad1d);
```
Now in the public API, this should be pretty easy to do when one of us gets some time (haha).

**Comment by jeremylt** [comment]
Cool! Basically, `RatelCreateBasisFromPlex()` from this commit:
https://gitlab.com/micromorph/ratel/-/merge_requests/30/diffs?commit_id=81929f94fab8b238e5142abe5a65375bfc22c72e
needs to make its way back into `examples/petsc/src/libceedsetup.c` But doing so will probably also mean updating `CeedLevelTransferSetup()` to use `CeedOperatorMultigridLevelCreate()` as well.

Since our use of `DMPlexCreateBoxMesh()` is embedded deeply in `bps.c`, we'll probably want to add a command line flag to swap back and  forth between tensor and simplex hexes. However we do it would also need to go into `multigrid.c`.

**Comment by rezgarshakeri** [comment]
Thanks for the instruction, I'll start probably next week.
