### ISSUE TITLE
Basic Fortran and Python Examples

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#459]
Currently we have Fortran examples provided via the tests and Nek and Python examples provided via the tests. We should create basic examples using the Fortran and Python interfaces.

See discussion here: https://github.com/CEED/libCEED/pull/446#discussion_r379080385

**Comment by valeriabarra** [comment]
I still have on my TODO list a PR dedicated to jupyter-notebook tutorials. I imagined them to be very simple, atomic tutorials that show one functionality/aspect at a time, like the snippets I have in my slides:
![Screenshot from 2020-02-13 13-36-46_3](https://user-images.githubusercontent.com/39932030/74476426-8bf5e480-4e66-11ea-9a68-9364fe3856d7.png)
![Screenshot from 2020-02-13 13-36-46_2](https://user-images.githubusercontent.com/39932030/74476427-8bf5e480-4e66-11ea-851b-9e32902ccdaf.png)
![Screenshot from 2020-02-13 13-36-46_1](https://user-images.githubusercontent.com/39932030/74476428-8c8e7b00-4e66-11ea-89a3-0f35573bfa3f.png)
![Screenshot from 2020-02-13 13-34-49](https://user-images.githubusercontent.com/39932030/74476430-8c8e7b00-4e66-11ea-88f6-7cfa7964bf4e.png)

And we could, of course, include more complicated, complete examples like `ex1`. 
Unfortunately, at this point, due to very limited time, I'm not sure when I get to sit on this.

**Comment by jedbrown** [comment]
Still pending on this issue:
- [ ] Best practices Fortran example(s)

**Comment by jedbrown** [comment]
I think the Python examples are fine. (Could be better, but we don't need an issue to track it.) For Fortran to be modern/idiomatic, we need to support a later standard, which is a major interface overhaul, thus I'll close this. Feel free to reopen.
