### ISSUE TITLE
-mtune=power9 is not working

### ISSUE THREAD

**Issue by YohannDudouit** [CEED/libCEED#467]
The makefile doesn't work out of the box on lassen:
```
make: 'lib' with optional backends: /cpu/self/memcheck/serial /cpu/self/memcheck/blocked /cpu/occa /gpu/occa /omp/occa /gpu/cuda/ref /gpu/cuda/reg /gpu/cuda/shared /gpu/cuda/gen
          CC build/interface/ceed-fortran.o
cc1: error: unrecognized argument in option '-mtune=power9'
```
Do you know if there is an easy fix to this?

**Comment by jedbrown** [comment]
Can you `make V=1` to get the full command line? I presume this is `-mtune=native` being unsupported. What compiler are you using and what flag do you think should be default in this setting?

**Comment by jeremylt** [comment]
@jedbrown, I think this is related to my (apparently bad) work to get the Makefile working on Travis's ppc64le cores.

Offending line of the Makefile:
```
MARCHFLAG := $(if $(shell $(CC) -E -march=native -x c /dev/null > /dev/null 2>&1 && echo 1),-march=native,-mtune=native)
```

**Comment by jedbrown** [comment]
I know the line of the makefile, but it passes `-mtune=native`, not `-mtune=power9`. I'd like to know exactly what is passed, but more importantly, I need to know what the desired option is on Lassen.

**Comment by YohannDudouit** [comment]
Here is the output of `make V=1`:
```
[dudouit1@lassen709:libCEED]$ make V=1
make: 'lib' with optional backends: /cpu/self/memcheck/serial /cpu/self/memcheck/blocked /gpu/cuda/ref /gpu/cuda/reg /gpu/cuda/shared /gpu/cuda/gen
gcc -I./include -I/usr/tce/packages/cuda/cuda-10.1.243/include -std=c99 -O -g -mtune=native -ffp-contract=fast -fopenmp-simd -Wall -Wextra -Wno-unused-parameter -fPIC -MMD -MP -DUNDERSCORE  -I/usr/tce/packages/cuda/cuda-10.1.243/include -c -o build/interface/ceed-fortran.o /g/g91/dudouit1/Projects/libCEED/interface/ceed-fortran.c
cc1: error: unrecognized argument in option '-mtune=power9'
cc1: note: valid arguments to '-mtune=' are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 powerpc powerpc64 powerpc64le rs64 titan
make: *** [Makefile:371: build/interface/ceed-fortran.o] Error 1
```
I'll try ask some people what is the expected value for `-mtune`

**Comment by YohannDudouit** [comment]
The expected values to compile for power9 on lassen are `-mcpu=powerpc64le -mtune=powerpc64le`

**Comment by jeremylt** [comment]
I'm surprised that `mtune=native` didn't populate the expected value. Does `mcpu=native` alone work?

**Comment by YohannDudouit** [comment]
Unfortunately, no.

**Comment by jedbrown** [comment]
I submitted a request to get access to Lassen. While that's pending, do you know what happens if you specify no `-mcpu` or `-mtune` options? Does it produce generic code or code for POWER9? I think `-mcpu=power9` is actually supported by later versions of GCC, we're just stuck with an older version and falling back to some reference instruction set. https://github.com/gcc-mirror/gcc/search?q=mcpu%3Dpower9&unscoped_q=mcpu%3Dpower9
And I suspect `-mcpu=native` works if you have a more recent GCC (at least that's what the docs say).

Also, by my read of the docs, it's redundant to use `-mtune=native` if you've already specified `-mcpu=native`. You'd use both if, for example, you want code to run on any power8, but optimize for power9, you'd pass `-cpu=power8 -mtune=power9`.

What do you think of
```
MARCHFLAG := $(if $(shell $(CC) -E -march=native -x c /dev/null > /dev/null 2>&1 && echo 1),-march=native,-mcpu=native)
```
and leave it to the user to pass `MARCHFLAG=-mcpu=power8` if the compiler is too old to handle it?

**Comment by YohannDudouit** [comment]
It is not a big problem to me, I just thought it could be interesting to see if we have an easy fix... which doesn't seem to be the case. I can indeed give the `MARCHFLAG` manually.
