### ISSUE TITLE
No Debugging Compile Flag

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#646]
We've previously discussed a compile flag to turn off the CeedErrorChk like PETSc has.

**Comment by jedbrown** [comment]
In PETSc, `--with-errorchecking=0` exists because of some historical doubters who believed these checks hurt performance. AFAIK, nobody actually uses it. If you're referring to `--with-debugging=0` (which circumvents various expensive things like memory checking and stack tracing), we don't really have those expensive things in libCEED.

What use case is this issue addressing?

**Comment by jeremylt** [comment]
I thought we'd talked about the first case. This came to mind because CeedErrorStore is getting more complicated, running through one or two chains of delegation.

**Comment by jedbrown** [comment]
That code path is only taken in case of an error (typically only once in the lifetime of a program) and can certainly be chosen dynamically (not compile-time).
