### ISSUE TITLE
Error/Exception Handling

### ISSUE THREAD

**Issue by FreddieWitherden** [CEED/libCEED#696]
I am currently reviewing libCEED as part of https://github.com/openjournals/joss-reviews/issues/2945.

One issue I've identified is around how errors are handled.  Specifically, standard operating procedure at the moment is along the lines of:
```
ierr = MightFail(); CeedChk(ierr);
```
where `CeedChk` expands to a return statement should `ierr` be non-zero.  This paradigm is problematic as it typically leaves the entity which the function is operating on in an undefined state.  This makes it virtually impossible for a user of libCEED do any meaningful error handling.  Moreover, it appears as if there several situations where this can result in memory being leaked; if a method allocates some memory (which succeeds) but then calls another internal method (which fails) the current code will immediately return without first freeing the temporary object it allocated.

There are also a few oddities.  For example:
https://github.com/CEED/libCEED/blob/06988bf74cc6ac18eacafe7930f080803395ba29/interface/ceed-operator.c#L67-L68
where the second `ierr` check appears to be redundant.

**Comment by knepley** [comment]
Don't you just use:
`ierr = MightFail();
if (ierr) {
  <do you cleanup>
  CeedChk(ierr);
}`
This is exactly what an exception implementation would do, without the bizarre exception discovery problems.

**Comment by jedbrown** [comment]
Thanks @FreddieWitherden. The case you mention is definitely a (harmless but for reader confusion) mistake. The broader complaint is super valid. libCEED has prioritized error behavior that is useful for callers (and library developers) to fix their code, which is usually what you want for compiled code, but not for interactive work where one wants to keep a valid state in a console/notebook environment. A common issue is that lower-level libraries (such as MPI) don't ensure leak-free valid state on errors, but since we want libCEED to be usable from interactive environments, I agree that it would make sense to at least communicate when an error is returning with valid state.

This becomes a really tall order (hard to implement correctly and hard to test) in the general case without type-level support, but I think we should at least cover the sort of cases that a Python or Julia user is likely to encounter in interactive environments (shape mismatch, incomplete specification of fields).

Cc: @jeremylt

**Comment by FreddieWitherden** [comment]
> Thanks @FreddieWitherden. The case you mention is definitely a (harmless but for reader confusion) mistake. The broader complaint is super valid. libCEED has prioritized error behavior that is useful for callers (and library developers) to fix their code, which is usually what you want for compiled code, but not for interactive work where one wants to keep a valid state in a console/notebook environment. A common issue is that lower-level libraries (such as MPI) don't ensure leak-free valid state on errors, but since we want libCEED to be usable from interactive environments, I agree that it would make sense to at least communicate when an error is returning with valid state.

In instances for errors are typically the result of user-error I've found the following two strategies helpful.

The first is simply to backtrace and exit upon encountering such an error.  This is nice as there is no possibility for a user to miss an error (say because they forgot to check a return code) and they always get a backtrace.  MPI implementations will sometimes do this if you really irk them, or at the least immediately write something out to stderr.

Another is to save the error state in a field variable on the associated object and check it before each API call.  For example
```
int myfun(Ceed *ceed)
{
    if (ceed->err) return CEED_INVALID_STATE;

    // ...
    int ierr = MightFail(); if (ierr) { ceed->err = ierr; ceed->err_file = __FILE__; ceed->err_line =  __LINE__; return ierr; }
}
```
then have a function such as `int CeedGetAndResetErr(ceed)` which fetches the error and resets the internal state.  (With similar ideas holding for related objects.)  This allows users of the C library to chain a set of mundane functions they do not expect will fail and handle the errors towards the end of a block but without a risk of missing where the error occurred.
