### ISSUE TITLE
Solids Example Load Increments

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#710]
Our current load increment strategy for the solids example is crude. We need to update this strategy to help reduce the number of load increments required at high order or high Poisson's ratio.

**Comment by jedbrown** [comment]
The arc-length section of Wriggers describes a class of algorithms that would be good for us to implement. Once that is implemented and we can reproduce some snap-through experiments (this page uses shell elements, but there's another with volume elements), we can investigate applying the continuation on coarse grids and with more compressible materials to accelerate convergence for difficult near-incompressible problems.
![image](https://user-images.githubusercontent.com/3303/110890937-30d33300-82ae-11eb-8510-d6a8e202156f.png)

**Comment by ArashMehraban** [comment]
Our way of choosing load increment is not efficient because we increase an external load vector (F_ext) gradually from 0 to reach to a desired value such as (F_des). This way, we assume that F_des itself remains constant during the simulation in terms of its _direction_ and only its magnitude is changing. Therefore, we control how the external load vector increases or decreases by introducing a scalar quantity such as \lambda. Thus by increasing or decreasing \lambda we can control our load increment. So, in essence, our residual is as follows:

R(u) = F_int (u) − \lambda * F_ext = 0

When Rich first showed me how ABAQUS can do these problems in 1 load increment, even some incompressible problems, I dug  into what ABAQUS does and some arc-length method a lot and here is findings:

In the above system of equations, we are interested in u and \lambda. Therefore,  at every load increment, we end upchanging the value of \lambda and try to determine u so that R(u) = 0 is satisfied above. The problem with that when used with Newton Method, convergence aside, is that the method fails to accurately follow the **equilibrium** path once the tangent stiffness reaches zero:

![newton](https://user-images.githubusercontent.com/10523693/110948329-115ff880-82f6-11eb-9cf9-1e3ba4af6ea7.png)

In essence, this method is able to solve "any" non-linear system of equations "very" efficiently but only up to the critical point if there are any.  We are circumventing this problems by utilizing **displacement control**, where we continuously increase the displacements u to remain on the equilibrium curve. That is why we have to guess how many load increments we need. Now, in addition to _snap through_ behaviors under load control, we may encounter problems with _snap back_ under displacement control. This figure shows an unstable situation under load control with snap-through:
![snap-through](https://user-images.githubusercontent.com/10523693/110949828-eb3b5800-82f7-11eb-93c0-b204c3729e79.png)

while this one shows a situation where snap-back encounters problems with load increment:
![snap-back](https://user-images.githubusercontent.com/10523693/110949933-12922500-82f8-11eb-9a3f-af7bfef8e758.png)

And finally, we have situations that naive load increment has an issue with both snap-though and snap-back:
![both-snap](https://user-images.githubusercontent.com/10523693/110950088-42d9c380-82f8-11eb-93da-0f675a8a9723.png)


As an alternative to the Newton-Method, the Arc Length method uses a simultaneous variation in both the displacements delta_u and the load vector delta_\lambda. In this method,  both delta_u and delta_\lambda are unknowns.  So the residual equation is now:

R(u) =  F_int (u_0 + delta_u) − (\lambda_0 + delta_\lambda) * q = 0

So, in the new residual, if the point (u_0 + delta_u , \lambda_0 + delta_\lambda) is satisfied, then the point belongs to the equilibrium path and solution may be updated successfully. However, it turns out satisfying the new residual is not feasible as we need some correction terms such as du and d_\lambda:

R_new(u) =  F_int (u_0 + delta_u + du) − (\lambda_0 + delta_\lambda + d_\lambda) * q

A little bit of manipulation with Taylor series expansion, we arrive at a system of equation that solves for du and d_\lambda which updates delta_u and delta_\lambda properly. This method has proven capable of handling problems involving a snapping behavior (limit points) and ABAQUS has an implementation of that. BUT, the draw back is in efficiency of this method. We would have to change the systems of equations to solve for both _du_ and _d_\lambda_ simultaneously.  

As an alternative, there is a 1983 paper by Crisfield whose algorithm appears to have been used (not sure how much changed over the years) in commercial FEA software such as ABAQUS. His method is a modification of arc-length method that does not require solving a new system of equation (R_new(u)  above). So, lets digress back to arc-length equation:
Let: K_T = [\partial{F_int} / \partial{u}], then arc-length after Taylor series mod is:

![z1](https://user-images.githubusercontent.com/10523693/110955168-2771b700-82fe-11eb-8bdb-1aeb9b0ee319.png)

where we have to solve for both _du_ and _d_\lambda_. Crisfield expressed the above equation as:
![z2](https://user-images.githubusercontent.com/10523693/110955424-71f33380-82fe-11eb-8101-61f487508d9e.png)
where
![z3](https://user-images.githubusercontent.com/10523693/110955480-820b1300-82fe-11eb-971b-7b27d6c3eefe.png)

We note that \bar{d_u} and du_t can be calculated immediately since they only require known information. Substituting this correction into arc-length yields:
![z4](https://user-images.githubusercontent.com/10523693/110955972-0067b500-82ff-11eb-8677-51b91422f2f3.png)
where
![z5](https://user-images.githubusercontent.com/10523693/110956096-21c8a100-82ff-11eb-83cb-766101b7de8f.png)
where
where \Psi and delta_l are user defined parameters. Here, delta_l defines how far to search for the next equilibrium
point and it is analogous (but not directly equivalent) to the load increment delta_lambda we used in Newton’s method. So we end up with a simple quadratic equation for d_\lambda to solve. Once d_\lambda is determined, it can be back substituted in: 
![z6](https://user-images.githubusercontent.com/10523693/110956697-bf23d500-82ff-11eb-8aac-ee8ec146b090.png)

to update the displacement variation and complete the iteration. So in every iteration,  \bar{d_u} and du_t need to be calculated
which can be done by exploiting the solver as Jacobian matrix is the same as in other methods. There is a drawback here. The quadratic equation has two solutions and therefore we end of with two du's. So we may go forward or backward:
![circle](https://user-images.githubusercontent.com/10523693/110958006-0fe7fd80-8301-11eb-99b1-7c5a51233b11.png)

A commonly used term "evolve forward"  is used in the field for going forward. It appears no one has found a universal method for all problems to evolve forward. However, for snap-through problems, "it is safe to argue that ‘next’ points in the ‘load-displacement’ equilibrium path will always cause the displacement to increase, and therefore the correct solution is the one that leads to a positive displacement variation delta_u". Obviously this does argument does not work with snap–back problems.
Of course, I have never implemented any of these methods. I have not consulted Wrigger's book either and I am not sure how this would help testing nearly compressible problems with the compressible formulation.

**Comment by jedbrown** [comment]
I think the figure 5.12 example from Wriggers above demonstrates that displacement may not increase (okay, this problem has both snap-back and snap-through within a single loading cycle). Wriggers has a table of different continuation variants that fit within a common algebraic framework. You can avoid solving the bordered system by adding a rank-1 correction. One can either solve two linear systems with the sparse operator or solve one using the sparse operator plus a rank 1 correction (Krylov methods are capable of picking up its effect without pushing it into the preconditioner).

I would like to develop these arc-length techniques here in the solid mechanics context and then port to PETSc SNES because they're relevant to lots of other problems. (I did some reading on these methods as a PhD student circa 2010 and it never rose to top priority to implement.)

**Comment by jedbrown** [comment]
You can unsubscribe from an issue on which you're participating by clicking in the right sidebar. I'd prefer to keep this open for the moment because the content is valuable, though the solution may be implemented in Ratel instead of here.
![image](https://user-images.githubusercontent.com/3303/143911441-6a65ca54-1749-49cc-8b06-e0c29748bb5f.png)

**Comment by ArashMehraban** [comment]
@jedbrown Yeah the content is really good. I consulted so many resources to make the above explanation for us. So keeping it open is great!

In terms unsubscribing from issues, I was referring to new development. For example, today @rezgarshakeri , had an update for the solids code:
`[CEED/libCEED] Solids: fixed duplicate definitions in structs.h (PR #848)`
But I did receive it. Is there anyway to completely unsubscribe?

Thanks

**Comment by jedbrown** [comment]
Up at the top.
![image](https://user-images.githubusercontent.com/3303/143914900-f09b76ed-132d-4b83-a694-f79822d043db.png)

**Comment by ArashMehraban** [comment]
@jedbrown Thanks :)

**Comment by jedbrown** [comment]
This has good discussion that @karenlstengel and/or @clmurphey may want to consider if looking at buckling problems, but the implementation would go in Ratel and/or PETSc so I'll close this issue.
