### ISSUE TITLE
OCCA Backend Builds Operator to Destroy

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#808]
See PR #806 

The OCCA backend currently checks the operator fields as part of destroying the operator. This doesn't really make any sense and it results in a CI failure in PR #806 

Offending code:
```C++
    int Operator::ceedDestroy(CeedOperator op) {
      delete Operator::from(op); // Is there a way to only delete this if its already been created?
      return CEED_ERROR_SUCCESS;
    }
```

It should be perfectly reasonable for a developer to create and then immediately destroy an operator as part of some incremental development process.

**Comment by dmed256** [comment]
Hi @jeremylt, I don't understand what the issue is here.

> The OCCA backend currently checks the operator fields as part of destroying the operator. This doesn't really make any sense 

What fields are we checking here? Is it something in the static `from`?

**Comment by jeremylt** [comment]
In the linked PR, we are making it an error to call CeedOperatorGetFields if the user has not finished specifying the fields. The result just isn't meaningful, useful, or accurate until the operator is fully specified.

But in the destructor for Operators in the OCCA backend, the constructor is called for the OCCA operator object, and inside of that constructor CeedOperatorGetFields is called. But this means that a OCCA Operator cannot be destroyed without fully specifying all fields.

But
a) I don't see why the destructor needs to call the constructor 
b) the user should be able to create and then immediately destroy an operator without error

**Comment by dmed256** [comment]
I think this comes from a misunderstanding on my part in the lifecycle of these objects. To be honest, I have no idea what the lifecycle of, in this case, the `CeedOperator` is. All I had to go with was source code examples and unit tests. If we allow for incomplete `CeedOperator` to be created, then you're right and we should handle that.

With that hopefully putting some context on why things were built this way, to answer the questions:

> a) I don't see why the destructor needs to call the constructor

We aren't allocating the `ceed::occa::Operator` objects in the destructor, we're only setting the fields since the `Operator::from()` is meant to fetch the current state of the `CeedOperator`. If we want to allow for partial creation of objects, then we should replace the destructors with something like:

```cpp
      Operator *operator_ = NULL;
      CeedOperatorGetData(op, (void**) &operator_);
      delete operator_;
```

The whole point of `Operator::from` is to centralize the wrapping of the `CeedOperator`, nothing more.

> b) the user should be able to create and then immediately destroy an operator without error

I think this was answered above that I assumed partially creating an object was not allowed.

Also, not really sure what this sentence was meant to convey...

>  The result just isn't meaningful, useful, or accurate until the operator is fully specified.

**Comment by dmed256** [comment]
PR: https://github.com/CEED/libCEED/pull/809

I can't seem to pull the C++11 flags so I can't test this PR locally 🤔 . I'll rely on the CICD checks for now

```
.../git/night/include/occa/dtype/builtins.hpp:90:37: warning: variadic templates are a C++11 extension [-Wc++11-extensions]
    template <class T = void, class ...Types>
```

**Comment by jeremylt** [comment]
> The result just isn't meaningful, useful, or accurate until the operator is fully specified.

This is just explaining why we're changing to this function call erroring on an incomplete object.

Thanks for the PR - it should be good to merge with one small fix.
