### ISSUE TITLE
Documentation Expansion

### ISSUE THREAD

**Issue by jeremylt** [CEED/libCEED#835]
Apparently @ArashMehraban has been approached by many engineers who wanted to use libCEED but it appeared too ambiguous to them. He is interested in expanding the documentation and examples to help support this need. (More details on these potential users and their needs would be helpful).

Two big requirements come to mind for any expansion to the documentation and examples:

1) Additional documentation must be a part of and extend the current documentation. We have put a lot of work into the current documentation and fragmenting our documentation and duplicating work does far more harm than good.

2) Additional examples must be tested in CI. See [t500-operator.c](https://github.com/CEED/libCEED/blob/main/tests/t500-operator.c) and the [documentation](https://libceed.readthedocs.io/en/latest/libCEEDapi/#api-description) for an example of incorporating snippets of tested code in documentation.

I think some of this could potentially be achieved by better advertising and testing @valeriabarra's fantastic Python tutorials. (We occasionally make minor interface changes but aren't very good at remembering to test all examples that aren't covered by CI)

**Comment by ArashMehraban** [comment]
Sounds great. We can incorporate the new expansions to whatever libCEED finds suitable. I’ll be in touch.

**Comment by jeremylt** [comment]
My point with 1) is that it would be most helpful if this additional work is designed to fit into the current documentation rather than being stuck in after the fact.

**Comment by ArashMehraban** [comment]
Yes. What I was referring to that once I create the images of the data
layout, their descriptions along with images and possible examples can go
into the already setup structure.

**Comment by ArashMehraban** [comment]
@jedbrown Yes!  I would say these folks are like Rich. Very knowledgeable with developing new constitutive laws and writing a Matlab code that only solves one problem ☺️, no convergence testing, etc. However, when I had deeper conversations with them about their models, I realized that what the want is parallelism that we could use PETSc while in my opinion their constitutive laws would very well fit under our Qfunctions. This was a multi-physics approach but the very essence of it would still fall under our solids code. However,  the way we code and PETSc is implemented is so foreign to them. I can elaborate on this much further but in one line, they do not see the pic picture and they do not see how to use our functions and the root of that is data layout to begin with. 

I have started a new position in CA, non-FEM related work, and I could have meetings and discussions with you after 5pm PST and the weekends for further elaboration and tell you what exactly I have in mind if that works.

**Comment by jeremylt** [comment]
I don't work in evenings and weekends (except in case of dire emergencies), but I think that we can get pretty far with communication on GitHub.

**Comment by ArashMehraban** [comment]
@jeremylt Fair😁

**Comment by ArashMehraban** [comment]
Sorry about the delay! I am trying to tune my schedule to be able to work on this in a rather consistent way that sporadically. To satisfy @jeremylt needs to work during normal business hours, the way i see this going forward is that I post something during non-business hours (typically after 5pm and/or the weekends) and wait for a reply during business hours from you.

Also, my current workspace is overleaf which is a personal choice which will not be changed until integration to whatever libCEED finds suitable later on. In essence, I do not wan to deal with .md, etc. files yet. It is not a priority.  
And finally quick update: I have worked out the High-Order PETSc section layout as of right now. I will share it this weekend.

**Comment by ArashMehraban** [comment]
After talking to the engineers in different companies, in my vision, we create this piece of the user manual with the following considerations:

1. We provide data layout and explain how our functions corresponds to these data layouts. The engineers know what to with data themselves.
2. Since libCEED is a secondary software utilized on top of others, the story of data flow starts from the main package such as PETSc. 
3. We needs to elaborate much more on the algorithms from 2010 paper, residual evaluation, action of Jacobian and then preconditioning

**Comment by jeremylt** [comment]
It feels like a lot of these goals can perhaps be best accomplished by leveraging and expanding the existing documentation on the interface and PETSc and examples, like here
https://libceed.readthedocs.io/en/latest/libCEEDapi/#api-description
and here
https://libceed.readthedocs.io/en/latest/examples/petsc/#petsc-demos-and-bps

**Comment by ArashMehraban** [comment]
Yes, Absolutely! Please note that I would like to add to that. Code is great and appreciated but I will add pictures, etc.

**Comment by ArashMehraban** [comment]
I decided to use this repo as the workspace instead of overleaf. I could simply draw things by hand and attach them here and you guys can comment easier. We can assemble everything into a proper document/place later.

I understand the following may not be entirely relevant to libCEED but the result of this in terms of vector of DoFs are used as "input" to libCEED:

@knepley is the following a fairly accurate explanation?

Lets start with **PETSc Section**, **Orientation** and **Dual Spaces**:

Lets consider a Quad mesh with 2 elements comprised of _cells_, _faces_ and _vertices_ in the picture below:

<img src="https://user-images.githubusercontent.com/10523693/140649091-aa9bad27-75a7-44f2-9a38-db46fee3ffb7.jpg" width="400" >

Without considering any orientation, the above doublet can be represented in memory as follows:

<img src="https://user-images.githubusercontent.com/10523693/140648833-dbc087fe-eb38-49bd-bc89-036e7088d7e8.jpg" width="150" >

and assume we are interested in utilizing this mesh Q<sub>3</sub> finite elements.  Therefore, if we use the nodal dual space, the DoFs will look like the following on our doublet:

<img src="https://user-images.githubusercontent.com/10523693/140649445-2f8d9f69-631a-4f11-ac67-d36e1e0d7968.jpg" width="400" >

Now the question is how are those DoFs going to be number in the doublet?

We first note that computations pertaining to FEM in PETSc occurs using reference elements. Therefore we provide a brief explanation of reference element in PETSc. Consider the following reference element:

<img src="https://user-images.githubusercontent.com/10523693/140650878-d7cd8f34-0478-4898-bb66-41044ed8de35.jpg" width="200">

Therefore the reference element orders  mesh points in the `closure` form as follows: 

<img src="https://user-images.githubusercontent.com/10523693/140650962-656212a6-87df-4361-8fb3-a2fe7f9370f3.jpg" height="100">

Therefore, it is safe to claim that for _affine-invariant_ finite elements, each DoF "belongs to", (or in the language of `DMPlex`, is supported in cells adjacent to) one mesh point. We recall that all cells, faces, edges and vertices are mesh points. Hence, a nodal DoF belongs to the mesh point of its coordinates. On the other hand, `PetscFE` orders DoFs on the reference element using the ordering of the mesh point:

<img src="https://user-images.githubusercontent.com/10523693/140651282-1ab340aa-0f07-4886-8402-ff9120d6459d.jpg" width="400">

Therefore the ordering above defines the following numbering on the physical element:

<img src="https://user-images.githubusercontent.com/10523693/140651366-44de4af5-140d-4224-9c1a-c044ebd936ea.jpg" width="400">

As a result of the above numbering we have the following `PetscSection`:

<img src="https://user-images.githubusercontent.com/10523693/140651446-0b854965-00dc-4ea1-89b4-8e8c7d4fb780.jpg" width="200">

So far we have established how DoFs are numbered in `DMPlex`. Next we established how they are used:
To reiterate, numerical computations for FEM is performed by utilizing the reference element ordering. Therefore, we need to know how to get the DoFs for reference elements from the physical mesh DoFs. It is best to explain this with an example. In our doublet above, consider cell `B: [b,e,f,g]` redrawn in such a way so that its edges are in the same places as their reference edges in `A_hat : [a_hat, b_hat, c_hat, d_hat ]` (picture below):

<img src="https://user-images.githubusercontent.com/10523693/140651928-513bc4db-d18d-4dc3-b627-4a5b1c1e8679.jpg" width="400">

But we notice the following:

<img src="https://user-images.githubusercontent.com/10523693/140652582-4c24dc0f-bdb1-420c-b7d4-eb85cff4e1d6.jpg" height="100">

The above difference between the reference and real element is resolved in the `cone` orientation. In essence,  `B` is not represented as `B: [b,e,f,g]`, it is represented as: `B: [b(backward), e(forward) , f(forward), g(forward)]`. Therefore, the reference DoFs that belong to `a_bar` can be determined from the real DoFs that belong to `b`. They just need to be reversed in this case. In addition, we note that we just worked out the simplest case for a 1D edge. There are more complicated situations, however, determining what orientation is the correct orientation for an element happens in `DMPlex` internally.

Finally, we  can use `DMPlex` in conjunction with `PetscFE`. In essence, when a _dual-space_ is used to create a `PetscSection` for a vector space of DoFs, it computes the necessary transformations for different orientations and attaches that to `section` as a `PetscSectionSym` object. 

The above makes our  `setupdm.c` for the solids code more clear where the PETSc's boiler plate is called in our `PetscFECreateByDegree()`. However, I think it is unfortunate that we used `P`and  `Q` for spaces in there. Although, from the context, it is obvious that these are not the `P`and  `Q` in libCEED, but we didn't have to use those either. 

Next, a vector of DoFs from DMPlex is created and libCEED vectors start dealing with them. I want the story with those vectors pictorially. Please note that pictures like the ones in the manual: https://libceed.readthedocs.io/en/latest/libCEEDapi/#api-description are very helpful, but I'm looking for a picture that depicts this:

Imagine, I have a vector from `DMPlex` for 4 `Hex8` elements for which each node has 3 DoFs. What does the restrictions do to this chuck?  

(I will come back to this document next week, mid-week, Tuesday or Wednesday)

**Comment by knepley** [comment]
That is a good explanation. I will make a few small points.

1. Dual basis vectors are truly attached to mesh points. Then we think of the nodal basis vector associated to a given dual vector as also associated to that mesh point.
2. The cone orientation numbers to elements of the dihedral group for that mesh point. When we are laying out a function space, those orientations are used to index group representation elements of the given dimension.
3. There is a closurePermutation that is performed when the dof closure is extracted. For example, we use this to get lexicographic dof ordering on tensor cells.

**Comment by ArashMehraban** [comment]
I need to close this as I have too many projects to deal with!
